// Code generated by protoc-gen-grpc-js-client
// source: credential.proto
// DO NOT EDIT!

/*
This is a RSVP based Ajax client for gRPC gateway JSON APIs.
*/

var xhr = require('grpc-xhr');

func CredentialsList(p, conf) {
	url = '/cloud/v1beta1/credentials'
	return xhr(url, 'GET', conf, p);
}

func CredentialsCreate(p, conf) {
	url = '/cloud/v1beta1/credentials'
	return xhr(url, 'POST', conf, null, p);
}

func CredentialsUpdate(p, conf) {
	url = '/cloud/v1beta1/credentials/' + p['name']
	delete p['name']
	return xhr(url, 'PUT', conf, null, p);
}

func CredentialsDelete(p, conf) {
	url = '/cloud/v1beta1/credentials/' + p['name']
	delete p['name']
	return xhr(url, 'DELETE', conf, p);
}

module.exports = {
  Credentials: {
      List: CredentialsList,
      Create: CredentialsCreate,
      Update: CredentialsUpdate,
      Delete: CredentialsDelete
  }
}
