// Code generated by protoc-gen-go.
// source: alert.proto
// DO NOT EDIT!

/*
Package alert is a generated protocol buffer package.

It is generated from these files:
	alert.proto
	notification.proto

It has these top-level messages:
	IcingaParam
	CheckInfluxData
	CheckKubernetes
	CommandParam
	IcingaState
	NotifierParam
	Alert
	AlertListRequest
	AlertListResponse
	CreateRequest
	UpdateRequest
	DeleteRequest
	Notification
	NotificationListRequest
	NotificationListResponse
	NotifyRequest
	AcknowledgeRequest
*/
package alert

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IcingaParam struct {
	CheckIntervalSec int64 `protobuf:"varint,1,opt,name=check_interval_sec,json=checkIntervalSec" json:"check_interval_sec,omitempty"`
	AlertIntervalSec int64 `protobuf:"varint,2,opt,name=alert_interval_sec,json=alertIntervalSec" json:"alert_interval_sec,omitempty"`
}

func (m *IcingaParam) Reset()                    { *m = IcingaParam{} }
func (m *IcingaParam) String() string            { return proto.CompactTextString(m) }
func (*IcingaParam) ProtoMessage()               {}
func (*IcingaParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CheckInfluxData struct {
	KubernetesNamespace string            `protobuf:"bytes,1,opt,name=kubernetes_namespace,json=kubernetesNamespace" json:"kubernetes_namespace,omitempty"`
	ObjectName          string            `protobuf:"bytes,2,opt,name=object_name,json=objectName" json:"object_name,omitempty"`
	Query               map[string]string `protobuf:"bytes,3,rep,name=query" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	R                   string            `protobuf:"bytes,4,opt,name=r" json:"r,omitempty"`
	WarningCondition    string            `protobuf:"bytes,5,opt,name=warning_condition,json=warningCondition" json:"warning_condition,omitempty"`
	CriticalCondition   string            `protobuf:"bytes,6,opt,name=critical_condition,json=criticalCondition" json:"critical_condition,omitempty"`
}

func (m *CheckInfluxData) Reset()                    { *m = CheckInfluxData{} }
func (m *CheckInfluxData) String() string            { return proto.CompactTextString(m) }
func (*CheckInfluxData) ProtoMessage()               {}
func (*CheckInfluxData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CheckInfluxData) GetQuery() map[string]string {
	if m != nil {
		return m.Query
	}
	return nil
}

type CheckKubernetes struct {
	Type     string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Count    int64  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Selector string `protobuf:"bytes,3,opt,name=selector" json:"selector,omitempty"`
}

func (m *CheckKubernetes) Reset()                    { *m = CheckKubernetes{} }
func (m *CheckKubernetes) String() string            { return proto.CompactTextString(m) }
func (*CheckKubernetes) ProtoMessage()               {}
func (*CheckKubernetes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CommandParam struct {
	CheckInfluxData *CheckInfluxData `protobuf:"bytes,1,opt,name=check_influx_data,json=checkInfluxData" json:"check_influx_data,omitempty"`
	CheckKubernetes *CheckKubernetes `protobuf:"bytes,2,opt,name=check_kubernetes,json=checkKubernetes" json:"check_kubernetes,omitempty"`
}

func (m *CommandParam) Reset()                    { *m = CommandParam{} }
func (m *CommandParam) String() string            { return proto.CompactTextString(m) }
func (*CommandParam) ProtoMessage()               {}
func (*CommandParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CommandParam) GetCheckInfluxData() *CheckInfluxData {
	if m != nil {
		return m.CheckInfluxData
	}
	return nil
}

func (m *CommandParam) GetCheckKubernetes() *CheckKubernetes {
	if m != nil {
		return m.CheckKubernetes
	}
	return nil
}

// This one is used in kubernetes/v0.1/client.proto
// To send information if alert is set for app/pod
type IcingaState struct {
	OK       int32 `protobuf:"varint,1,opt,name=OK,json=oK" json:"OK,omitempty"`
	Warning  int32 `protobuf:"varint,2,opt,name=Warning,json=warning" json:"Warning,omitempty"`
	Critical int32 `protobuf:"varint,3,opt,name=Critical,json=critical" json:"Critical,omitempty"`
	Unknown  int32 `protobuf:"varint,4,opt,name=Unknown,json=unknown" json:"Unknown,omitempty"`
}

func (m *IcingaState) Reset()                    { *m = IcingaState{} }
func (m *IcingaState) String() string            { return proto.CompactTextString(m) }
func (*IcingaState) ProtoMessage()               {}
func (*IcingaState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type NotifierParam struct {
	State   string `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	UserUid string `protobuf:"bytes,2,opt,name=user_uid,json=userUid" json:"user_uid,omitempty"`
	Method  string `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
}

func (m *NotifierParam) Reset()                    { *m = NotifierParam{} }
func (m *NotifierParam) String() string            { return proto.CompactTextString(m) }
func (*NotifierParam) ProtoMessage()               {}
func (*NotifierParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Alert struct {
	Phid          string           `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	Cluster       string           `protobuf:"bytes,2,opt,name=cluster" json:"cluster,omitempty"`
	Plugin        string           `protobuf:"bytes,3,opt,name=plugin" json:"plugin,omitempty"`
	IcingaService string           `protobuf:"bytes,4,opt,name=icinga_service,json=icingaService" json:"icinga_service,omitempty"`
	IcingaParam   *IcingaParam     `protobuf:"bytes,5,opt,name=icinga_param,json=icingaParam" json:"icinga_param,omitempty"`
	CheckCommand  string           `protobuf:"bytes,6,opt,name=check_command,json=checkCommand" json:"check_command,omitempty"`
	CommandParam  *CommandParam    `protobuf:"bytes,7,opt,name=command_param,json=commandParam" json:"command_param,omitempty"`
	NotifierParam []*NotifierParam `protobuf:"bytes,8,rep,name=notifier_param,json=notifierParam" json:"notifier_param,omitempty"`
	IcingawebUrl  string           `protobuf:"bytes,9,opt,name=icingaweb_url,json=icingawebUrl" json:"icingaweb_url,omitempty"`
}

func (m *Alert) Reset()                    { *m = Alert{} }
func (m *Alert) String() string            { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()               {}
func (*Alert) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Alert) GetIcingaParam() *IcingaParam {
	if m != nil {
		return m.IcingaParam
	}
	return nil
}

func (m *Alert) GetCommandParam() *CommandParam {
	if m != nil {
		return m.CommandParam
	}
	return nil
}

func (m *Alert) GetNotifierParam() []*NotifierParam {
	if m != nil {
		return m.NotifierParam
	}
	return nil
}

type AlertListRequest struct {
	Cluster             string `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Plugin              string `protobuf:"bytes,2,opt,name=plugin" json:"plugin,omitempty"`
	KubernetesNamespace string `protobuf:"bytes,3,opt,name=kubernetes_namespace,json=kubernetesNamespace" json:"kubernetes_namespace,omitempty"`
	ObjectName          string `protobuf:"bytes,4,opt,name=object_name,json=objectName" json:"object_name,omitempty"`
}

func (m *AlertListRequest) Reset()                    { *m = AlertListRequest{} }
func (m *AlertListRequest) String() string            { return proto.CompactTextString(m) }
func (*AlertListRequest) ProtoMessage()               {}
func (*AlertListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type AlertListResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Alerts []*Alert       `protobuf:"bytes,2,rep,name=alerts" json:"alerts,omitempty"`
}

func (m *AlertListResponse) Reset()                    { *m = AlertListResponse{} }
func (m *AlertListResponse) String() string            { return proto.CompactTextString(m) }
func (*AlertListResponse) ProtoMessage()               {}
func (*AlertListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AlertListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AlertListResponse) GetAlerts() []*Alert {
	if m != nil {
		return m.Alerts
	}
	return nil
}

type CreateRequest struct {
	Cluster       string           `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Plugin        string           `protobuf:"bytes,2,opt,name=plugin" json:"plugin,omitempty"`
	IcingaService string           `protobuf:"bytes,3,opt,name=icinga_service,json=icingaService" json:"icinga_service,omitempty"`
	IcingaParam   *IcingaParam     `protobuf:"bytes,4,opt,name=icinga_param,json=icingaParam" json:"icinga_param,omitempty"`
	CheckCommand  string           `protobuf:"bytes,5,opt,name=check_command,json=checkCommand" json:"check_command,omitempty"`
	CommandParam  *CommandParam    `protobuf:"bytes,6,opt,name=command_param,json=commandParam" json:"command_param,omitempty"`
	NotifierParam []*NotifierParam `protobuf:"bytes,7,rep,name=notifier_param,json=notifierParam" json:"notifier_param,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CreateRequest) GetIcingaParam() *IcingaParam {
	if m != nil {
		return m.IcingaParam
	}
	return nil
}

func (m *CreateRequest) GetCommandParam() *CommandParam {
	if m != nil {
		return m.CommandParam
	}
	return nil
}

func (m *CreateRequest) GetNotifierParam() []*NotifierParam {
	if m != nil {
		return m.NotifierParam
	}
	return nil
}

type UpdateRequest struct {
	Phid          string           `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	IcingaParam   *IcingaParam     `protobuf:"bytes,2,opt,name=icinga_param,json=icingaParam" json:"icinga_param,omitempty"`
	CommandParam  *CommandParam    `protobuf:"bytes,3,opt,name=command_param,json=commandParam" json:"command_param,omitempty"`
	NotifierParam []*NotifierParam `protobuf:"bytes,4,rep,name=notifier_param,json=notifierParam" json:"notifier_param,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UpdateRequest) GetIcingaParam() *IcingaParam {
	if m != nil {
		return m.IcingaParam
	}
	return nil
}

func (m *UpdateRequest) GetCommandParam() *CommandParam {
	if m != nil {
		return m.CommandParam
	}
	return nil
}

func (m *UpdateRequest) GetNotifierParam() []*NotifierParam {
	if m != nil {
		return m.NotifierParam
	}
	return nil
}

type DeleteRequest struct {
	Phid string `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*IcingaParam)(nil), "alert.IcingaParam")
	proto.RegisterType((*CheckInfluxData)(nil), "alert.CheckInfluxData")
	proto.RegisterType((*CheckKubernetes)(nil), "alert.CheckKubernetes")
	proto.RegisterType((*CommandParam)(nil), "alert.CommandParam")
	proto.RegisterType((*IcingaState)(nil), "alert.IcingaState")
	proto.RegisterType((*NotifierParam)(nil), "alert.NotifierParam")
	proto.RegisterType((*Alert)(nil), "alert.Alert")
	proto.RegisterType((*AlertListRequest)(nil), "alert.AlertListRequest")
	proto.RegisterType((*AlertListResponse)(nil), "alert.AlertListResponse")
	proto.RegisterType((*CreateRequest)(nil), "alert.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "alert.UpdateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "alert.DeleteRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Alerts service

type AlertsClient interface {
	List(ctx context.Context, in *AlertListRequest, opts ...grpc.CallOption) (*AlertListResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
}

type alertsClient struct {
	cc *grpc.ClientConn
}

func NewAlertsClient(cc *grpc.ClientConn) AlertsClient {
	return &alertsClient{cc}
}

func (c *alertsClient) List(ctx context.Context, in *AlertListRequest, opts ...grpc.CallOption) (*AlertListResponse, error) {
	out := new(AlertListResponse)
	err := grpc.Invoke(ctx, "/alert.Alerts/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/alert.Alerts/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/alert.Alerts/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertsClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/alert.Alerts/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Alerts service

type AlertsServer interface {
	List(context.Context, *AlertListRequest) (*AlertListResponse, error)
	Create(context.Context, *CreateRequest) (*dtypes.VoidResponse, error)
	Update(context.Context, *UpdateRequest) (*dtypes.VoidResponse, error)
	Delete(context.Context, *DeleteRequest) (*dtypes.VoidResponse, error)
}

func RegisterAlertsServer(s *grpc.Server, srv AlertsServer) {
	s.RegisterService(&_Alerts_serviceDesc, srv)
}

func _Alerts_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alert.Alerts/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServer).List(ctx, req.(*AlertListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alerts_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alert.Alerts/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alerts_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alert.Alerts/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alerts_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alert.Alerts/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Alerts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "alert.Alerts",
	HandlerType: (*AlertsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Alerts_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Alerts_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Alerts_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Alerts_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("alert.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 967 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x56, 0xcf, 0x6e, 0x1b, 0x45,
	0x18, 0xd7, 0xae, 0xbd, 0xeb, 0xe4, 0xb3, 0x9d, 0x26, 0x53, 0x2b, 0x18, 0x0b, 0xa9, 0xed, 0xa6,
	0x94, 0x28, 0x05, 0x9b, 0x04, 0x21, 0xa2, 0x72, 0x2a, 0x2e, 0x87, 0x2a, 0xa8, 0xc0, 0x46, 0xa1,
	0xdc, 0xcc, 0x78, 0x77, 0xea, 0x0c, 0x59, 0xcf, 0x6c, 0x67, 0x66, 0x13, 0x22, 0xc4, 0x85, 0x57,
	0x40, 0x48, 0x5c, 0x78, 0x12, 0x6e, 0xbc, 0x01, 0xe2, 0x15, 0x38, 0xf2, 0x10, 0x68, 0xfe, 0xac,
	0xbd, 0x76, 0x1a, 0x62, 0xe5, 0x62, 0xed, 0xf7, 0x67, 0xbf, 0x6f, 0x7f, 0x7f, 0x66, 0x64, 0x68,
	0xe2, 0x8c, 0x08, 0xd5, 0xcf, 0x05, 0x57, 0x1c, 0x05, 0x26, 0xe8, 0xbd, 0x33, 0xe1, 0x7c, 0x92,
	0x91, 0x01, 0xce, 0xe9, 0x00, 0x33, 0xc6, 0x15, 0x56, 0x94, 0x33, 0x69, 0x9b, 0x7a, 0xdb, 0x3a,
	0x9d, 0xaa, 0xcb, 0x9c, 0xc8, 0x81, 0xf9, 0xb5, 0xf9, 0x88, 0x42, 0xf3, 0x79, 0x42, 0xd9, 0x04,
	0x7f, 0x85, 0x05, 0x9e, 0xa2, 0xf7, 0x01, 0x25, 0xa7, 0x24, 0x39, 0x1b, 0x51, 0xa6, 0x88, 0x38,
	0xc7, 0xd9, 0x48, 0x92, 0xa4, 0xeb, 0xdd, 0xf7, 0x76, 0x6b, 0xf1, 0xa6, 0xa9, 0x3c, 0x77, 0x85,
	0x63, 0x92, 0xe8, 0x6e, 0xb3, 0x7b, 0xb1, 0xdb, 0xb7, 0xdd, 0xa6, 0x52, 0xe9, 0x8e, 0xfe, 0xf4,
	0xe1, 0xce, 0xd0, 0x8e, 0x78, 0x95, 0x15, 0x3f, 0x3c, 0xc3, 0x0a, 0xa3, 0x7d, 0xe8, 0x9c, 0x15,
	0x63, 0x22, 0x18, 0x51, 0x44, 0x8e, 0x18, 0x9e, 0x12, 0x99, 0xe3, 0x84, 0x98, 0x8d, 0xeb, 0xf1,
	0xdd, 0x79, 0xed, 0x45, 0x59, 0x42, 0xf7, 0xa0, 0xc9, 0xc7, 0xdf, 0x93, 0x44, 0x99, 0x76, 0xb3,
	0x6d, 0x3d, 0x06, 0x9b, 0xd2, 0x5d, 0xe8, 0x13, 0x08, 0x5e, 0x17, 0x44, 0x5c, 0x76, 0x6b, 0xf7,
	0x6b, 0xbb, 0xcd, 0x83, 0x07, 0x7d, 0x4b, 0xd6, 0xd2, 0xea, 0xfe, 0xd7, 0xba, 0xe7, 0x73, 0xa6,
	0xc4, 0x65, 0x6c, 0xfb, 0x51, 0x0b, 0x3c, 0xd1, 0xad, 0x9b, 0x79, 0x9e, 0x40, 0x8f, 0x61, 0xeb,
	0x02, 0x0b, 0x46, 0xd9, 0x64, 0x94, 0x70, 0x96, 0x52, 0xcd, 0x66, 0x37, 0x30, 0xd5, 0x4d, 0x57,
	0x18, 0x96, 0x79, 0xf4, 0x01, 0xa0, 0x44, 0x50, 0x45, 0x13, 0x9c, 0x55, 0xba, 0x43, 0xd3, 0xbd,
	0x55, 0x56, 0x66, 0xed, 0xbd, 0x43, 0x80, 0xf9, 0x7a, 0xb4, 0x09, 0xb5, 0x33, 0x72, 0xe9, 0x30,
	0xeb, 0x47, 0xd4, 0x81, 0xe0, 0x1c, 0x67, 0x45, 0x89, 0xce, 0x06, 0x4f, 0xfc, 0x43, 0x2f, 0x7a,
	0xe9, 0x38, 0x3c, 0x9a, 0x31, 0x83, 0x10, 0xd4, 0xb5, 0xa2, 0xee, 0x7d, 0xf3, 0xac, 0x07, 0x24,
	0xbc, 0x60, 0xca, 0x89, 0x61, 0x03, 0xd4, 0x83, 0x35, 0x49, 0x32, 0x92, 0x28, 0x2e, 0xba, 0x35,
	0xd3, 0x3d, 0x8b, 0xa3, 0x5f, 0x3d, 0x68, 0x0d, 0xf9, 0x74, 0x8a, 0x59, 0x6a, 0xad, 0xf0, 0x19,
	0x6c, 0x95, 0x56, 0xd0, 0x9c, 0x8d, 0x52, 0xac, 0xb0, 0xd9, 0xd1, 0x3c, 0xd8, 0x7e, 0x33, 0xa5,
	0xf1, 0x9d, 0x64, 0x49, 0xde, 0xa7, 0x60, 0x4d, 0x33, 0x9a, 0x0b, 0x69, 0xbe, 0x68, 0x69, 0xc4,
	0x1c, 0x8c, 0x1b, 0x31, 0x4f, 0x44, 0xd3, 0xd2, 0xa0, 0xc7, 0x0a, 0x2b, 0x82, 0x36, 0xc0, 0xff,
	0xf2, 0xc8, 0x7c, 0x46, 0x10, 0xfb, 0xfc, 0x08, 0x75, 0xa1, 0xf1, 0xd2, 0x8a, 0x61, 0x06, 0x07,
	0x71, 0xc3, 0x69, 0xa3, 0xc1, 0x0e, 0x1d, 0xf1, 0x06, 0x6c, 0x10, 0xaf, 0x95, 0x42, 0xe8, 0xb7,
	0x4e, 0xd8, 0x19, 0xe3, 0x17, 0xcc, 0xe8, 0x1d, 0xc4, 0x8d, 0xc2, 0x86, 0xd1, 0xb7, 0xd0, 0x7e,
	0xc1, 0x15, 0x7d, 0x45, 0x89, 0xb0, 0x34, 0x74, 0x20, 0x90, 0x7a, 0xb3, 0xa3, 0xd7, 0x06, 0xe8,
	0x6d, 0x58, 0x2b, 0x24, 0x11, 0xa3, 0x82, 0xa6, 0x4e, 0xa3, 0x86, 0x8e, 0x4f, 0x68, 0x8a, 0xb6,
	0x21, 0x9c, 0x12, 0x75, 0xca, 0x53, 0x47, 0xb1, 0x8b, 0xa2, 0x7f, 0x7d, 0x08, 0x9e, 0x6a, 0xcc,
	0x5a, 0xb0, 0xfc, 0x94, 0xa6, 0xa5, 0x60, 0xfa, 0x59, 0x7f, 0x51, 0x92, 0x15, 0x52, 0x11, 0x51,
	0xce, 0x73, 0xa1, 0x9e, 0x97, 0x67, 0xc5, 0x84, 0xb2, 0x72, 0x9e, 0x8d, 0xd0, 0xbb, 0xb0, 0x41,
	0x0d, 0x31, 0x23, 0x49, 0xc4, 0x39, 0x4d, 0x88, 0xb3, 0x6e, 0xdb, 0x66, 0x8f, 0x6d, 0x12, 0x7d,
	0x0c, 0x2d, 0xd7, 0x96, 0x6b, 0x3c, 0xc6, 0xc1, 0xcd, 0x03, 0xe4, 0xe8, 0xaf, 0x9c, 0xfd, 0xb8,
	0x49, 0x2b, 0x17, 0xc1, 0x0e, 0xb4, 0xad, 0x72, 0x89, 0xf5, 0x84, 0xf3, 0x72, 0xcb, 0x24, 0x9d,
	0x4f, 0xd0, 0x21, 0xb4, 0x5d, 0xd9, 0x0d, 0x6f, 0x98, 0xe1, 0x77, 0x4b, 0x6d, 0x2b, 0x76, 0x8a,
	0x5b, 0x49, 0xd5, 0x5c, 0x9f, 0xc2, 0x06, 0x73, 0x34, 0xbb, 0x57, 0xd7, 0xcc, 0x61, 0xed, 0xb8,
	0x57, 0x17, 0x34, 0x88, 0xdb, 0x6c, 0x41, 0x92, 0x1d, 0x70, 0x18, 0x2f, 0xc8, 0x78, 0x54, 0x88,
	0xac, 0xbb, 0x6e, 0xbf, 0x6d, 0x96, 0x3c, 0x11, 0x59, 0xf4, 0x9b, 0x07, 0x9b, 0x86, 0xee, 0x2f,
	0xa8, 0x54, 0x31, 0x79, 0x5d, 0x10, 0xa9, 0xaa, 0x2c, 0x7b, 0xd7, 0xb1, 0xec, 0x2f, 0xb0, 0x7c,
	0xdd, 0x05, 0x55, 0x5b, 0xf9, 0x82, 0xaa, 0x2f, 0x5f, 0x50, 0x11, 0x86, 0xad, 0xca, 0x97, 0xc9,
	0x9c, 0x33, 0x49, 0xd0, 0x23, 0x08, 0xb5, 0xb5, 0x0a, 0xe9, 0xce, 0xd8, 0x46, 0xdf, 0xde, 0xd6,
	0xfd, 0x63, 0x93, 0x8d, 0x5d, 0x15, 0x3d, 0x84, 0xd0, 0x50, 0xa4, 0x0f, 0x92, 0x66, 0xac, 0xe5,
	0x18, 0x33, 0x13, 0x63, 0x57, 0x8b, 0xfe, 0xf0, 0xa1, 0x3d, 0x14, 0x04, 0x2b, 0x72, 0x7b, 0xe8,
	0x57, 0x0d, 0x56, 0x5b, 0xc5, 0x60, 0xf5, 0x5b, 0x1a, 0x2c, 0x58, 0xc5, 0x60, 0xe1, 0xed, 0x0d,
	0xd6, 0x58, 0xd9, 0x60, 0xd1, 0x5f, 0x1e, 0xb4, 0x4f, 0xf2, 0xb4, 0xc2, 0xde, 0x9b, 0x8e, 0xec,
	0x32, 0x70, 0x7f, 0x35, 0xe0, 0x57, 0x30, 0xd5, 0x6e, 0x8f, 0xa9, 0xbe, 0x3a, 0xa6, 0x1d, 0x68,
	0x3f, 0x23, 0x19, 0xf9, 0x5f, 0x48, 0x07, 0xbf, 0xd7, 0x20, 0x34, 0x46, 0x92, 0x68, 0x0c, 0x75,
	0xed, 0x4f, 0xf4, 0x56, 0xd5, 0x5f, 0x95, 0xb3, 0xd4, 0xeb, 0x5e, 0x2d, 0x58, 0x2b, 0x47, 0xef,
	0xfd, 0xfc, 0xf7, 0x3f, 0xbf, 0xf8, 0x0f, 0xd0, 0xbd, 0x01, 0xce, 0x73, 0x99, 0xf0, 0xd4, 0xfd,
	0x29, 0xd1, 0x8d, 0x83, 0xf3, 0x0f, 0xfb, 0xfb, 0xf6, 0x51, 0xa2, 0xef, 0x20, 0xb4, 0x26, 0x45,
	0x25, 0x84, 0x05, 0xcf, 0xf6, 0x3a, 0xe5, 0x19, 0xf8, 0x86, 0xd3, 0x74, 0x36, 0x7e, 0xcf, 0x8c,
	0x7f, 0xd8, 0xbb, 0x69, 0xfc, 0x13, 0x6f, 0x0f, 0x4d, 0x20, 0xb4, 0x42, 0xce, 0x36, 0x2c, 0xe8,
	0x7a, 0xcd, 0x86, 0x7d, 0xb3, 0xe1, 0x71, 0xf4, 0xe8, 0x86, 0x0d, 0x83, 0x1f, 0x35, 0x6b, 0x3f,
	0xe9, 0x45, 0x29, 0x84, 0x96, 0xde, 0xd9, 0xa2, 0x05, 0xb6, 0xaf, 0x59, 0xd4, 0x37, 0x8b, 0x76,
	0xf7, 0x56, 0x5c, 0x34, 0x0e, 0xcd, 0x9f, 0xb6, 0x8f, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xca,
	0xa5, 0xd9, 0xd5, 0x00, 0x0a, 0x00, 0x00,
}
