// Code generated by protoc-gen-go.
// source: agent.proto
// DO NOT EDIT!

/*
Package v1beta1 is a generated protocol buffer package.

It is generated from these files:
	agent.proto
	build.proto
	job.proto
	master.proto

It has these top-level messages:
	AgentListRequest
	AgentListResponse
	Agent
	AgentCreateRequest
	PortInfo
	AgentDescribeRequest
	AgentDescribeResponse
	AgentDeleteRequest
	AgentRestartRequest
	AgentRestartResponse
	BuildDescribeRequest
	BuildDescribeResponse
	BuildListRequest
	BuildListResponse
	Build
	JobListRequest
	JobListResponse
	JobBuildRequest
	JobDescribeRequest
	JobDescribeResponse
	JobHealth
	JobDeleteRequest
	JobCreateRequest
	JobCopyRequest
	Job
	MasterCreateRequest
	MasterDeleteRequest
*/
package v1beta1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/appscodeapis/appscode/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AgentListRequest struct {
	// List of status to get the agent filterd on the status
	// values in
	//   PENDING
	//   FAILED
	//   ONLINE
	//   OFFLINE
	//   DELETED
	Status []string `protobuf:"bytes,1,rep,name=status" json:"status,omitempty"`
}

func (m *AgentListRequest) Reset()                    { *m = AgentListRequest{} }
func (m *AgentListRequest) String() string            { return proto.CompactTextString(m) }
func (*AgentListRequest) ProtoMessage()               {}
func (*AgentListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AgentListResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Agents []*Agent       `protobuf:"bytes,2,rep,name=agents" json:"agents,omitempty"`
}

func (m *AgentListResponse) Reset()                    { *m = AgentListResponse{} }
func (m *AgentListResponse) String() string            { return proto.CompactTextString(m) }
func (*AgentListResponse) ProtoMessage()               {}
func (*AgentListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AgentListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AgentListResponse) GetAgents() []*Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

type Agent struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Status      string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	AgentStatus string `protobuf:"bytes,3,opt,name=agent_status,json=agentStatus" json:"agent_status,omitempty"`
	IsRefreshed int32  `protobuf:"varint,4,opt,name=is_refreshed,json=isRefreshed" json:"is_refreshed,omitempty"`
	CreatedAt   int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt   int64  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Agent) Reset()                    { *m = Agent{} }
func (m *Agent) String() string            { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()               {}
func (*Agent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type AgentCreateRequest struct {
	Sku               string      `protobuf:"bytes,1,opt,name=sku" json:"sku,omitempty"`
	Executors         int32       `protobuf:"varint,2,opt,name=executors" json:"executors,omitempty"`
	Labels            string      `protobuf:"bytes,3,opt,name=labels" json:"labels,omitempty"`
	UserStartupScript string      `protobuf:"bytes,4,opt,name=user_startup_script,json=userStartupScript" json:"user_startup_script,omitempty"`
	SaltbaseVersion   string      `protobuf:"bytes,5,opt,name=saltbase_version,json=saltbaseVersion" json:"saltbase_version,omitempty"`
	CiStarterVersion  string      `protobuf:"bytes,6,opt,name=ci_starter_version,json=ciStarterVersion" json:"ci_starter_version,omitempty"`
	Ports             []*PortInfo `protobuf:"bytes,7,rep,name=ports" json:"ports,omitempty"`
	Role              string      `protobuf:"bytes,8,opt,name=role" json:"role,omitempty"`
}

func (m *AgentCreateRequest) Reset()                    { *m = AgentCreateRequest{} }
func (m *AgentCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*AgentCreateRequest) ProtoMessage()               {}
func (*AgentCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AgentCreateRequest) GetPorts() []*PortInfo {
	if m != nil {
		return m.Ports
	}
	return nil
}

type PortInfo struct {
	Protocol  string `protobuf:"bytes,1,opt,name=protocol" json:"protocol,omitempty"`
	PortRange string `protobuf:"bytes,2,opt,name=port_range,json=portRange" json:"port_range,omitempty"`
}

func (m *PortInfo) Reset()                    { *m = PortInfo{} }
func (m *PortInfo) String() string            { return proto.CompactTextString(m) }
func (*PortInfo) ProtoMessage()               {}
func (*PortInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type AgentDescribeRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *AgentDescribeRequest) Reset()                    { *m = AgentDescribeRequest{} }
func (m *AgentDescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*AgentDescribeRequest) ProtoMessage()               {}
func (*AgentDescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type AgentDescribeResponse struct {
	Status           *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Name             string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Executors        int64          `protobuf:"varint,3,opt,name=executors" json:"executors,omitempty"`
	AgentStatus      string         `protobuf:"bytes,4,opt,name=agent_status,json=agentStatus" json:"agent_status,omitempty"`
	AgentStatusCause string         `protobuf:"bytes,5,opt,name=agent_status_cause,json=agentStatusCause" json:"agent_status_cause,omitempty"`
	Label            string         `protobuf:"bytes,6,opt,name=label" json:"label,omitempty"`
	Provider         string         `protobuf:"bytes,7,opt,name=provider" json:"provider,omitempty"`
	Sku              string         `protobuf:"bytes,8,opt,name=sku" json:"sku,omitempty"`
	StartupScript    string         `protobuf:"bytes,9,opt,name=startup_script,json=startupScript" json:"startup_script,omitempty"`
	CreatedAt        int64          `protobuf:"varint,10,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt        int64          `protobuf:"varint,11,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *AgentDescribeResponse) Reset()                    { *m = AgentDescribeResponse{} }
func (m *AgentDescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*AgentDescribeResponse) ProtoMessage()               {}
func (*AgentDescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AgentDescribeResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type AgentDeleteRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *AgentDeleteRequest) Reset()                    { *m = AgentDeleteRequest{} }
func (m *AgentDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*AgentDeleteRequest) ProtoMessage()               {}
func (*AgentDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type AgentRestartRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *AgentRestartRequest) Reset()                    { *m = AgentRestartRequest{} }
func (m *AgentRestartRequest) String() string            { return proto.CompactTextString(m) }
func (*AgentRestartRequest) ProtoMessage()               {}
func (*AgentRestartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type AgentRestartResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *AgentRestartResponse) Reset()                    { *m = AgentRestartResponse{} }
func (m *AgentRestartResponse) String() string            { return proto.CompactTextString(m) }
func (*AgentRestartResponse) ProtoMessage()               {}
func (*AgentRestartResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *AgentRestartResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*AgentListRequest)(nil), "ci.v1beta1.AgentListRequest")
	proto.RegisterType((*AgentListResponse)(nil), "ci.v1beta1.AgentListResponse")
	proto.RegisterType((*Agent)(nil), "ci.v1beta1.Agent")
	proto.RegisterType((*AgentCreateRequest)(nil), "ci.v1beta1.AgentCreateRequest")
	proto.RegisterType((*PortInfo)(nil), "ci.v1beta1.PortInfo")
	proto.RegisterType((*AgentDescribeRequest)(nil), "ci.v1beta1.AgentDescribeRequest")
	proto.RegisterType((*AgentDescribeResponse)(nil), "ci.v1beta1.AgentDescribeResponse")
	proto.RegisterType((*AgentDeleteRequest)(nil), "ci.v1beta1.AgentDeleteRequest")
	proto.RegisterType((*AgentRestartRequest)(nil), "ci.v1beta1.AgentRestartRequest")
	proto.RegisterType((*AgentRestartResponse)(nil), "ci.v1beta1.AgentRestartResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Agents service

type AgentsClient interface {
	List(ctx context.Context, in *AgentListRequest, opts ...grpc.CallOption) (*AgentListResponse, error)
	Describe(ctx context.Context, in *AgentDescribeRequest, opts ...grpc.CallOption) (*AgentDescribeResponse, error)
	Create(ctx context.Context, in *AgentCreateRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error)
	Delete(ctx context.Context, in *AgentDeleteRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error)
	Restart(ctx context.Context, in *AgentRestartRequest, opts ...grpc.CallOption) (*AgentRestartResponse, error)
}

type agentsClient struct {
	cc *grpc.ClientConn
}

func NewAgentsClient(cc *grpc.ClientConn) AgentsClient {
	return &agentsClient{cc}
}

func (c *agentsClient) List(ctx context.Context, in *AgentListRequest, opts ...grpc.CallOption) (*AgentListResponse, error) {
	out := new(AgentListResponse)
	err := grpc.Invoke(ctx, "/ci.v1beta1.Agents/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsClient) Describe(ctx context.Context, in *AgentDescribeRequest, opts ...grpc.CallOption) (*AgentDescribeResponse, error) {
	out := new(AgentDescribeResponse)
	err := grpc.Invoke(ctx, "/ci.v1beta1.Agents/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsClient) Create(ctx context.Context, in *AgentCreateRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error) {
	out := new(dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/ci.v1beta1.Agents/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsClient) Delete(ctx context.Context, in *AgentDeleteRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error) {
	out := new(dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/ci.v1beta1.Agents/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsClient) Restart(ctx context.Context, in *AgentRestartRequest, opts ...grpc.CallOption) (*AgentRestartResponse, error) {
	out := new(AgentRestartResponse)
	err := grpc.Invoke(ctx, "/ci.v1beta1.Agents/Restart", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Agents service

type AgentsServer interface {
	List(context.Context, *AgentListRequest) (*AgentListResponse, error)
	Describe(context.Context, *AgentDescribeRequest) (*AgentDescribeResponse, error)
	Create(context.Context, *AgentCreateRequest) (*dtypes.LongRunningResponse, error)
	Delete(context.Context, *AgentDeleteRequest) (*dtypes.LongRunningResponse, error)
	Restart(context.Context, *AgentRestartRequest) (*AgentRestartResponse, error)
}

func RegisterAgentsServer(s *grpc.Server, srv AgentsServer) {
	s.RegisterService(&_Agents_serviceDesc, srv)
}

func _Agents_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ci.v1beta1.Agents/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServer).List(ctx, req.(*AgentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agents_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ci.v1beta1.Agents/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServer).Describe(ctx, req.(*AgentDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agents_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ci.v1beta1.Agents/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServer).Create(ctx, req.(*AgentCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agents_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ci.v1beta1.Agents/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServer).Delete(ctx, req.(*AgentDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agents_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ci.v1beta1.Agents/Restart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServer).Restart(ctx, req.(*AgentRestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agents_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ci.v1beta1.Agents",
	HandlerType: (*AgentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Agents_List_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _Agents_Describe_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Agents_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Agents_Delete_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _Agents_Restart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 804 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x55, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x05, 0xf5, 0xa0, 0xc4, 0xab, 0xd6, 0x95, 0xc7, 0xae, 0x41, 0xa8, 0x7e, 0xc8, 0x44, 0x6b,
	0xc8, 0x82, 0x2b, 0xd6, 0x6e, 0x8b, 0x02, 0x5d, 0x14, 0x70, 0xed, 0x2c, 0x02, 0x78, 0x11, 0x50,
	0x40, 0x16, 0xd9, 0x08, 0x23, 0x6a, 0xac, 0x10, 0x51, 0x38, 0xcc, 0xcc, 0xd0, 0x49, 0x60, 0x64,
	0x63, 0x20, 0xdb, 0x00, 0x41, 0xbe, 0x21, 0x9f, 0x10, 0xe4, 0x43, 0xf2, 0x0b, 0xd9, 0xe5, 0x27,
	0x82, 0x79, 0x50, 0x22, 0x25, 0x5b, 0xb6, 0x37, 0x02, 0xe7, 0xdc, 0x33, 0xf7, 0x79, 0xe6, 0x0a,
	0x1a, 0x78, 0x4c, 0x62, 0xd1, 0x4b, 0x18, 0x15, 0x14, 0x41, 0x18, 0xf5, 0x2e, 0x0e, 0x87, 0x44,
	0xe0, 0xc3, 0xd6, 0xe6, 0x98, 0xd2, 0xf1, 0x84, 0xf8, 0x38, 0x89, 0x7c, 0x1c, 0xc7, 0x54, 0x60,
	0x11, 0xd1, 0x98, 0x6b, 0x66, 0x6b, 0x1b, 0x27, 0x09, 0x0f, 0xe9, 0xe8, 0x26, 0xfb, 0x86, 0x84,
	0x47, 0xe2, 0x75, 0x42, 0xb8, 0xaf, 0x7e, 0x35, 0xee, 0x75, 0xa1, 0x79, 0x2c, 0x03, 0x9e, 0x45,
	0x5c, 0x04, 0xe4, 0x45, 0x4a, 0xb8, 0x40, 0x1b, 0x60, 0x73, 0x81, 0x45, 0xca, 0x5d, 0xab, 0x5d,
	0xee, 0x38, 0x81, 0x39, 0x79, 0xe7, 0xb0, 0x9a, 0xe3, 0xf2, 0x84, 0xc6, 0x9c, 0xa0, 0xbd, 0x1c,
	0xd9, 0xea, 0x34, 0x8e, 0x56, 0x7a, 0x3a, 0x4a, 0xaf, 0xaf, 0xd0, 0xec, 0x32, 0xda, 0x07, 0x5b,
	0x55, 0xc6, 0xdd, 0x52, 0xbb, 0xdc, 0x69, 0x1c, 0xad, 0xf6, 0x66, 0xb5, 0xf5, 0x94, 0xdb, 0xc0,
	0x10, 0xbc, 0xcf, 0x16, 0x54, 0x15, 0x82, 0x10, 0x54, 0x62, 0xfc, 0x9c, 0x28, 0xd7, 0x4e, 0xa0,
	0xbe, 0x73, 0xd9, 0x95, 0x14, 0x9a, 0x05, 0xd8, 0x85, 0x1f, 0xd4, 0xfd, 0x81, 0xb1, 0x96, 0x95,
	0x55, 0xb7, 0xb3, 0x3f, 0xa5, 0x44, 0x7c, 0xc0, 0xc8, 0x39, 0x23, 0xfc, 0x29, 0x19, 0xb9, 0x95,
	0xb6, 0xd5, 0xa9, 0x06, 0x8d, 0x88, 0x07, 0x19, 0x84, 0xb6, 0x00, 0x42, 0x46, 0xb0, 0x20, 0xa3,
	0x01, 0x16, 0x6e, 0xb5, 0x6d, 0x75, 0xca, 0x81, 0x63, 0x90, 0x63, 0x21, 0xcd, 0x69, 0x32, 0xca,
	0xcc, 0xb6, 0x36, 0x1b, 0xe4, 0x58, 0x78, 0x1f, 0x4b, 0x80, 0x54, 0xe6, 0x27, 0xea, 0x46, 0xd6,
	0xd0, 0x26, 0x94, 0xf9, 0xb3, 0xd4, 0x54, 0x21, 0x3f, 0xd1, 0x26, 0x38, 0xe4, 0x15, 0x09, 0x53,
	0x41, 0x99, 0xae, 0xa3, 0x1a, 0xcc, 0x00, 0x59, 0xe2, 0x04, 0x0f, 0xc9, 0x24, 0x2b, 0xc2, 0x9c,
	0x50, 0x0f, 0xd6, 0x52, 0x4e, 0x98, 0xac, 0x90, 0x89, 0x34, 0x19, 0xf0, 0x90, 0x45, 0x89, 0x50,
	0x65, 0x38, 0xc1, 0xaa, 0x34, 0xf5, 0xb5, 0xa5, 0xaf, 0x0c, 0x68, 0x1f, 0x9a, 0x1c, 0x4f, 0xc4,
	0x10, 0x73, 0x32, 0xb8, 0x20, 0x8c, 0x47, 0x34, 0x56, 0x25, 0x39, 0xc1, 0x4f, 0x19, 0xfe, 0x58,
	0xc3, 0xe8, 0x00, 0x50, 0x18, 0x69, 0xc7, 0x84, 0x4d, 0xc9, 0xb6, 0x22, 0x37, 0xc3, 0xa8, 0xaf,
	0x0d, 0x19, 0xbb, 0x0b, 0xd5, 0x84, 0x32, 0xc1, 0xdd, 0x9a, 0x9a, 0xe5, 0x7a, 0x7e, 0x96, 0x8f,
	0x28, 0x13, 0x0f, 0xe3, 0x73, 0x1a, 0x68, 0x8a, 0x9c, 0x21, 0xa3, 0x13, 0xe2, 0xd6, 0xf5, 0x0c,
	0xe5, 0xb7, 0xf7, 0x00, 0xea, 0x19, 0x0d, 0xb5, 0xa0, 0xae, 0xa4, 0x18, 0xd2, 0x89, 0xe9, 0xd0,
	0xf4, 0x2c, 0xdb, 0x2d, 0x9d, 0x0c, 0x18, 0x8e, 0xc7, 0xc4, 0xcc, 0xdb, 0x91, 0x48, 0x20, 0x01,
	0xaf, 0x0b, 0xeb, 0xaa, 0xdb, 0xa7, 0x44, 0x76, 0x62, 0x38, 0xed, 0xf7, 0x35, 0xb2, 0xf1, 0xbe,
	0x95, 0xe0, 0xe7, 0x39, 0xf2, 0x3d, 0x15, 0x9c, 0x79, 0x2d, 0xe5, 0xc4, 0x58, 0x98, 0x63, 0x59,
	0xcb, 0x61, 0x36, 0xc7, 0x79, 0x49, 0x56, 0x16, 0x25, 0x79, 0x00, 0x28, 0x4f, 0x19, 0x84, 0x38,
	0xe5, 0xc4, 0x0c, 0xa9, 0x99, 0x23, 0x9e, 0x48, 0x1c, 0xad, 0x43, 0x55, 0x49, 0xc1, 0x0c, 0x46,
	0x1f, 0x4c, 0x07, 0x2f, 0xa2, 0x11, 0x61, 0x6e, 0x6d, 0xda, 0x41, 0x75, 0xce, 0xa4, 0x57, 0x9f,
	0x49, 0xef, 0x37, 0x58, 0x99, 0xd3, 0x8f, 0xa3, 0x8c, 0x3f, 0xf2, 0x82, 0x76, 0x8a, 0x0f, 0x01,
	0x96, 0x3f, 0x84, 0xc6, 0xfc, 0x43, 0xe8, 0x98, 0x77, 0x70, 0x4a, 0x26, 0x44, 0x2c, 0x9d, 0xcb,
	0x3e, 0xac, 0xe9, 0xd7, 0x4f, 0x54, 0xfc, 0x65, 0xd4, 0xff, 0xcc, 0xb8, 0xa7, 0xd4, 0xfb, 0x0d,
	0xf0, 0xe8, 0x5d, 0x15, 0x6c, 0xe5, 0x80, 0x23, 0x06, 0x15, 0xb9, 0xc5, 0xd0, 0xe6, 0xc2, 0x16,
	0xca, 0x2d, 0xc2, 0xd6, 0xd6, 0x0d, 0x56, 0x1d, 0xd7, 0xfb, 0xfd, 0xea, 0x93, 0x5b, 0xaa, 0x5b,
	0x57, 0x5f, 0xbe, 0x7e, 0x28, 0xed, 0xa2, 0x1d, 0xbf, 0xb0, 0x82, 0xc3, 0xc8, 0x37, 0x37, 0x7d,
	0xbd, 0xd6, 0xd0, 0x5b, 0x0b, 0xea, 0x99, 0xf8, 0x50, 0x7b, 0xc1, 0xf5, 0x9c, 0x88, 0x5b, 0xbb,
	0x4b, 0x18, 0x26, 0x81, 0xbf, 0x72, 0x09, 0x74, 0xd0, 0xde, 0x2d, 0x09, 0xf8, 0x97, 0xb2, 0x8b,
	0x6f, 0xd0, 0x4b, 0xb0, 0xf5, 0x7a, 0x42, 0xdb, 0x0b, 0x21, 0x0a, 0x7b, 0xab, 0xf5, 0x4b, 0xd6,
	0xc8, 0x33, 0x1a, 0x8f, 0x83, 0x34, 0x8e, 0xa3, 0x78, 0x3c, 0x0d, 0xfe, 0x47, 0x2e, 0xf8, 0xaf,
	0xde, 0x6d, 0xd5, 0xff, 0x6b, 0x75, 0xd1, 0x25, 0xd8, 0x5a, 0x0f, 0xd7, 0x04, 0x2e, 0x08, 0x65,
	0x79, 0xe0, 0x42, 0xd5, 0xdd, 0xbb, 0x56, 0xfd, 0xde, 0x82, 0x9a, 0x11, 0x0e, 0xda, 0x59, 0xfc,
	0xef, 0x29, 0xa8, 0xaf, 0xd5, 0xbe, 0x99, 0x60, 0x92, 0x38, 0xc9, 0x25, 0xf1, 0x8f, 0xf7, 0xf7,
	0xdd, 0x92, 0xf0, 0x71, 0xa8, 0xfe, 0x93, 0x7d, 0x46, 0x86, 0x94, 0x8a, 0xff, 0x9d, 0x27, 0x35,
	0xc3, 0x1b, 0xda, 0x6a, 0xe7, 0xfd, 0xf9, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x30, 0x4c, 0x97, 0x8f,
	0xff, 0x07, 0x00, 0x00,
}
