// Code generated by protoc-gen-grpc-js-client
// source: loadbalancer.proto
// DO NOT EDIT!

/*
This is a RSVP based Ajax client for gRPC gateway JSON APIs.
*/

var xhr = require('grpc-xhr');

func LoadBalancersList(p, conf) {
	path = '/kubernetes/v1beta1/clusters/' + p['cluster'] + '/loadbalancers'
	delete p['cluster']
	return xhr(path, 'GET', conf, p);
}

func LoadBalancersDescribe(p, conf) {
	path = '/kubernetes/v1beta1/clusters/' + p['cluster'] + '/loadbalancers/' + p['name']
	delete p['cluster']
	delete p['name']
	return xhr(path, 'GET', conf, p);
}

func LoadBalancersCreate(p, conf) {
	path = '/kubernetes/v1beta1/clusters/' + p['cluster'] + '/loadbalancers'
	delete p['cluster']
	return xhr(path, 'POST', conf, null, p);
}

func LoadBalancersUpdate(p, conf) {
	path = '/kubernetes/v1beta1/clusters/' + p['cluster'] + '/loadbalancers/' + p['name']
	delete p['cluster']
	delete p['name']
	return xhr(path, 'PUT', conf, null, p);
}

func LoadBalancersDelete(p, conf) {
	path = '/kubernetes/v1beta1/clusters/' + p['cluster'] + '/loadbalancers/' + p['name']
	delete p['cluster']
	delete p['name']
	return xhr(path, 'DELETE', conf, p);
}

module.exports = {
  LoadBalancers: {
      List: LoadBalancersList,
      Describe: LoadBalancersDescribe,
      Create: LoadBalancersCreate,
      Update: LoadBalancersUpdate,
      Delete: LoadBalancersDelete
  }
}
