// Code generated by protoc-gen-go.
// source: acmeuser.proto
// DO NOT EDIT!

/*
Package v1beta1 is a generated protocol buffer package.

It is generated from these files:
	acmeuser.proto
	ca.proto
	certificate.proto

It has these top-level messages:
	AcmeUserRegisterRequest
	AcmeUserRegisterResponse
	CACreateRequest
	CACreateResponse
	CertificateListRequest
	CertificateListResponse
	CertificateDescribeRequest
	CertificateDescribeResponse
	CertificateCreateRequest
	SubjectInfo
	CertificateCreateResponse
	Certificate
	CertificateImportRequest
	CertificateDeleteRequest
	CertificateRenewRequest
	CertificateRenewResponse
	CertificateRevokeRequest
	CertificateDeployRequest
	DNSCheckRequest
*/
package v1beta1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import appscode_dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AcmeUserRegisterRequest struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *AcmeUserRegisterRequest) Reset()                    { *m = AcmeUserRegisterRequest{} }
func (m *AcmeUserRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*AcmeUserRegisterRequest) ProtoMessage()               {}
func (*AcmeUserRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AcmeUserRegisterResponse struct {
	Status *appscode_dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Phid   string                  `protobuf:"bytes,2,opt,name=phid" json:"phid,omitempty"`
}

func (m *AcmeUserRegisterResponse) Reset()                    { *m = AcmeUserRegisterResponse{} }
func (m *AcmeUserRegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*AcmeUserRegisterResponse) ProtoMessage()               {}
func (*AcmeUserRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AcmeUserRegisterResponse) GetStatus() *appscode_dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*AcmeUserRegisterRequest)(nil), "appscode.certificate.v1beta1.AcmeUserRegisterRequest")
	proto.RegisterType((*AcmeUserRegisterResponse)(nil), "appscode.certificate.v1beta1.AcmeUserRegisterResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for AcmeUsers service

type AcmeUsersClient interface {
	Register(ctx context.Context, in *AcmeUserRegisterRequest, opts ...grpc.CallOption) (*AcmeUserRegisterResponse, error)
}

type acmeUsersClient struct {
	cc *grpc.ClientConn
}

func NewAcmeUsersClient(cc *grpc.ClientConn) AcmeUsersClient {
	return &acmeUsersClient{cc}
}

func (c *acmeUsersClient) Register(ctx context.Context, in *AcmeUserRegisterRequest, opts ...grpc.CallOption) (*AcmeUserRegisterResponse, error) {
	out := new(AcmeUserRegisterResponse)
	err := grpc.Invoke(ctx, "/appscode.certificate.v1beta1.AcmeUsers/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AcmeUsers service

type AcmeUsersServer interface {
	Register(context.Context, *AcmeUserRegisterRequest) (*AcmeUserRegisterResponse, error)
}

func RegisterAcmeUsersServer(s *grpc.Server, srv AcmeUsersServer) {
	s.RegisterService(&_AcmeUsers_serviceDesc, srv)
}

func _AcmeUsers_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcmeUserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcmeUsersServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.certificate.v1beta1.AcmeUsers/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcmeUsersServer).Register(ctx, req.(*AcmeUserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AcmeUsers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appscode.certificate.v1beta1.AcmeUsers",
	HandlerType: (*AcmeUsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AcmeUsers_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("acmeuser.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4a, 0xc4, 0x30,
	0x14, 0xc6, 0xe9, 0xa0, 0xa3, 0x8d, 0xe0, 0x22, 0x88, 0x53, 0xca, 0x2c, 0xa4, 0x2b, 0x17, 0x9a,
	0x30, 0xe3, 0x9f, 0xbd, 0x1e, 0xa1, 0xe2, 0xc6, 0x8d, 0xbc, 0x69, 0x9f, 0x35, 0x30, 0x6d, 0x62,
	0xdf, 0xab, 0xe0, 0xd6, 0x2b, 0x78, 0x10, 0x4f, 0xe0, 0x29, 0xbc, 0x82, 0x07, 0x91, 0x26, 0xad,
	0x08, 0xa2, 0xe0, 0xa6, 0x4d, 0xbe, 0xe4, 0xf7, 0xbe, 0xbc, 0xef, 0x89, 0x5d, 0x28, 0x6a, 0xec,
	0x08, 0x5b, 0xe5, 0x5a, 0xcb, 0x56, 0xce, 0xc1, 0x39, 0x2a, 0x6c, 0x89, 0xaa, 0xc0, 0x96, 0xcd,
	0x9d, 0x29, 0x80, 0x51, 0x3d, 0x2e, 0x56, 0xc8, 0xb0, 0x48, 0xe7, 0x95, 0xb5, 0xd5, 0x1a, 0x35,
	0x38, 0xa3, 0xa1, 0x69, 0x2c, 0x03, 0x1b, 0xdb, 0x50, 0x60, 0xd3, 0xfd, 0x5e, 0x2e, 0xf9, 0xc9,
	0x21, 0x69, 0xff, 0x0d, 0x7a, 0xa6, 0xc5, 0xec, 0xa2, 0xa8, 0xf1, 0x9a, 0xb0, 0xcd, 0xb1, 0x32,
	0xc4, 0xfd, 0xff, 0xa1, 0x43, 0x62, 0xb9, 0x27, 0x36, 0xb1, 0x06, 0xb3, 0x4e, 0xa2, 0x83, 0xe8,
	0x30, 0xce, 0xc3, 0x26, 0xbb, 0x15, 0xc9, 0x4f, 0x80, 0x9c, 0x6d, 0x08, 0xa5, 0x16, 0x53, 0x62,
	0xe0, 0x8e, 0x3c, 0xb2, 0xb3, 0x9c, 0xa9, 0xaf, 0x17, 0x07, 0x6b, 0x75, 0xe5, 0x8f, 0xf3, 0xe1,
	0x9a, 0x94, 0x62, 0xc3, 0xdd, 0x9b, 0x32, 0x99, 0x78, 0x07, 0xbf, 0x5e, 0xbe, 0x45, 0x22, 0x1e,
	0x1d, 0x48, 0xbe, 0x46, 0x62, 0x7b, 0xf4, 0x91, 0x67, 0xea, 0xaf, 0x04, 0xd4, 0x2f, 0x8d, 0xa4,
	0xe7, 0xff, 0xc5, 0x42, 0x3b, 0xd9, 0xe9, 0xf3, 0xfb, 0xc7, 0xcb, 0x44, 0xa5, 0x47, 0x7a, 0xe4,
	0x7d, 0xb8, 0xdf, 0x6a, 0xe8, 0xa1, 0x86, 0xee, 0x27, 0x75, 0xdc, 0x8f, 0x8a, 0x2e, 0xe3, 0x9b,
	0xad, 0x41, 0x5d, 0x4d, 0x7d, 0xc6, 0x27, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xfe, 0xb0,
	0x1e, 0xc9, 0x01, 0x00, 0x00,
}
