// Code generated by protoc-gen-grpc-gateway-cors
// source: acmeuser.proto
// DO NOT EDIT!

/*
Package v1beta1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package v1beta1

import "github.com/grpc-ecosystem/grpc-gateway/runtime"

// ExportAcmeUsersCorsPatterns returns an array of grpc gatway mux patterns for
// AcmeUsers service to enable CORS.
func ExportAcmeUsersCorsPatterns() []runtime.Pattern {
	return []runtime.Pattern{}
}
