// Code generated by protoc-gen-go.
// source: certificate.proto
// DO NOT EDIT!

/*
Package v1beta1 is a generated protocol buffer package.

It is generated from these files:
	certificate.proto

It has these top-level messages:
	CertificateListRequest
	CertificateListResponse
	CertificateDescribeRequest
	CertificateDescribeResponse
	Certificate
	CertificateLoadRequest
	CertificateDeleteRequest
	CertificateDeployRequest
*/
package v1beta1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/appscodeapis/appscode/api"
import appscode_dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CertificateListRequest struct {
}

func (m *CertificateListRequest) Reset()                    { *m = CertificateListRequest{} }
func (m *CertificateListRequest) String() string            { return proto.CompactTextString(m) }
func (*CertificateListRequest) ProtoMessage()               {}
func (*CertificateListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CertificateListResponse struct {
	Status       *appscode_dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Certificates []*Certificate          `protobuf:"bytes,2,rep,name=certificates" json:"certificates,omitempty"`
}

func (m *CertificateListResponse) Reset()                    { *m = CertificateListResponse{} }
func (m *CertificateListResponse) String() string            { return proto.CompactTextString(m) }
func (*CertificateListResponse) ProtoMessage()               {}
func (*CertificateListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CertificateListResponse) GetStatus() *appscode_dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CertificateListResponse) GetCertificates() []*Certificate {
	if m != nil {
		return m.Certificates
	}
	return nil
}

type CertificateDescribeRequest struct {
	Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *CertificateDescribeRequest) Reset()                    { *m = CertificateDescribeRequest{} }
func (m *CertificateDescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*CertificateDescribeRequest) ProtoMessage()               {}
func (*CertificateDescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CertificateDescribeRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CertificateDescribeResponse struct {
	Status      *appscode_dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Certificate *Certificate            `protobuf:"bytes,2,opt,name=certificate" json:"certificate,omitempty"`
}

func (m *CertificateDescribeResponse) Reset()                    { *m = CertificateDescribeResponse{} }
func (m *CertificateDescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*CertificateDescribeResponse) ProtoMessage()               {}
func (*CertificateDescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CertificateDescribeResponse) GetStatus() *appscode_dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CertificateDescribeResponse) GetCertificate() *Certificate {
	if m != nil {
		return m.Certificate
	}
	return nil
}

type Certificate struct {
	Phid       string `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	CommonName string `protobuf:"bytes,3,opt,name=common_name,json=commonName" json:"common_name,omitempty"`
	IssuedBy   string `protobuf:"bytes,4,opt,name=issued_by,json=issuedBy" json:"issued_by,omitempty"`
	ValidFrom  int64  `protobuf:"varint,5,opt,name=valid_from,json=validFrom" json:"valid_from,omitempty"`
	ExpireDate int64  `protobuf:"varint,6,opt,name=expire_date,json=expireDate" json:"expire_date,omitempty"`
	// those feilds will not included into list response.
	// only describe response will include the underlying
	// feilds.
	Sans         []string `protobuf:"bytes,7,rep,name=sans" json:"sans,omitempty"`
	Cert         string   `protobuf:"bytes,8,opt,name=cert" json:"cert,omitempty"`
	Key          string   `protobuf:"bytes,9,opt,name=key" json:"key,omitempty"`
	Version      int32    `protobuf:"varint,10,opt,name=version" json:"version,omitempty"`
	SerialNumber string   `protobuf:"bytes,11,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
}

func (m *Certificate) Reset()                    { *m = Certificate{} }
func (m *Certificate) String() string            { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()               {}
func (*Certificate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Certificate) GetPhid() string {
	if m != nil {
		return m.Phid
	}
	return ""
}

func (m *Certificate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Certificate) GetCommonName() string {
	if m != nil {
		return m.CommonName
	}
	return ""
}

func (m *Certificate) GetIssuedBy() string {
	if m != nil {
		return m.IssuedBy
	}
	return ""
}

func (m *Certificate) GetValidFrom() int64 {
	if m != nil {
		return m.ValidFrom
	}
	return 0
}

func (m *Certificate) GetExpireDate() int64 {
	if m != nil {
		return m.ExpireDate
	}
	return 0
}

func (m *Certificate) GetSans() []string {
	if m != nil {
		return m.Sans
	}
	return nil
}

func (m *Certificate) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

func (m *Certificate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Certificate) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Certificate) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

type CertificateLoadRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CertData string `protobuf:"bytes,2,opt,name=cert_data,json=certData" json:"cert_data,omitempty"`
	KeyData  string `protobuf:"bytes,3,opt,name=key_data,json=keyData" json:"key_data,omitempty"`
}

func (m *CertificateLoadRequest) Reset()                    { *m = CertificateLoadRequest{} }
func (m *CertificateLoadRequest) String() string            { return proto.CompactTextString(m) }
func (*CertificateLoadRequest) ProtoMessage()               {}
func (*CertificateLoadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CertificateLoadRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CertificateLoadRequest) GetCertData() string {
	if m != nil {
		return m.CertData
	}
	return ""
}

func (m *CertificateLoadRequest) GetKeyData() string {
	if m != nil {
		return m.KeyData
	}
	return ""
}

type CertificateDeleteRequest struct {
	Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *CertificateDeleteRequest) Reset()                    { *m = CertificateDeleteRequest{} }
func (m *CertificateDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*CertificateDeleteRequest) ProtoMessage()               {}
func (*CertificateDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CertificateDeleteRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CertificateDeployRequest struct {
	Uid         string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	SecretName  string `protobuf:"bytes,2,opt,name=secret_name,json=secretName" json:"secret_name,omitempty"`
	ClusterName string `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName" json:"cluster_name,omitempty"`
	Namespace   string `protobuf:"bytes,4,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *CertificateDeployRequest) Reset()                    { *m = CertificateDeployRequest{} }
func (m *CertificateDeployRequest) String() string            { return proto.CompactTextString(m) }
func (*CertificateDeployRequest) ProtoMessage()               {}
func (*CertificateDeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CertificateDeployRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CertificateDeployRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *CertificateDeployRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *CertificateDeployRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func init() {
	proto.RegisterType((*CertificateListRequest)(nil), "appscode.certificate.v1beta1.CertificateListRequest")
	proto.RegisterType((*CertificateListResponse)(nil), "appscode.certificate.v1beta1.CertificateListResponse")
	proto.RegisterType((*CertificateDescribeRequest)(nil), "appscode.certificate.v1beta1.CertificateDescribeRequest")
	proto.RegisterType((*CertificateDescribeResponse)(nil), "appscode.certificate.v1beta1.CertificateDescribeResponse")
	proto.RegisterType((*Certificate)(nil), "appscode.certificate.v1beta1.Certificate")
	proto.RegisterType((*CertificateLoadRequest)(nil), "appscode.certificate.v1beta1.CertificateLoadRequest")
	proto.RegisterType((*CertificateDeleteRequest)(nil), "appscode.certificate.v1beta1.CertificateDeleteRequest")
	proto.RegisterType((*CertificateDeployRequest)(nil), "appscode.certificate.v1beta1.CertificateDeployRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Certificates service

type CertificatesClient interface {
	List(ctx context.Context, in *CertificateListRequest, opts ...grpc.CallOption) (*CertificateListResponse, error)
	Describe(ctx context.Context, in *CertificateDescribeRequest, opts ...grpc.CallOption) (*CertificateDescribeResponse, error)
	Load(ctx context.Context, in *CertificateLoadRequest, opts ...grpc.CallOption) (*appscode_dtypes.VoidResponse, error)
	Delete(ctx context.Context, in *CertificateDeleteRequest, opts ...grpc.CallOption) (*appscode_dtypes.VoidResponse, error)
	Deploy(ctx context.Context, in *CertificateDeployRequest, opts ...grpc.CallOption) (*appscode_dtypes.VoidResponse, error)
}

type certificatesClient struct {
	cc *grpc.ClientConn
}

func NewCertificatesClient(cc *grpc.ClientConn) CertificatesClient {
	return &certificatesClient{cc}
}

func (c *certificatesClient) List(ctx context.Context, in *CertificateListRequest, opts ...grpc.CallOption) (*CertificateListResponse, error) {
	out := new(CertificateListResponse)
	err := grpc.Invoke(ctx, "/appscode.certificate.v1beta1.Certificates/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificatesClient) Describe(ctx context.Context, in *CertificateDescribeRequest, opts ...grpc.CallOption) (*CertificateDescribeResponse, error) {
	out := new(CertificateDescribeResponse)
	err := grpc.Invoke(ctx, "/appscode.certificate.v1beta1.Certificates/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificatesClient) Load(ctx context.Context, in *CertificateLoadRequest, opts ...grpc.CallOption) (*appscode_dtypes.VoidResponse, error) {
	out := new(appscode_dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/appscode.certificate.v1beta1.Certificates/Load", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificatesClient) Delete(ctx context.Context, in *CertificateDeleteRequest, opts ...grpc.CallOption) (*appscode_dtypes.VoidResponse, error) {
	out := new(appscode_dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/appscode.certificate.v1beta1.Certificates/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificatesClient) Deploy(ctx context.Context, in *CertificateDeployRequest, opts ...grpc.CallOption) (*appscode_dtypes.VoidResponse, error) {
	out := new(appscode_dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/appscode.certificate.v1beta1.Certificates/Deploy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Certificates service

type CertificatesServer interface {
	List(context.Context, *CertificateListRequest) (*CertificateListResponse, error)
	Describe(context.Context, *CertificateDescribeRequest) (*CertificateDescribeResponse, error)
	Load(context.Context, *CertificateLoadRequest) (*appscode_dtypes.VoidResponse, error)
	Delete(context.Context, *CertificateDeleteRequest) (*appscode_dtypes.VoidResponse, error)
	Deploy(context.Context, *CertificateDeployRequest) (*appscode_dtypes.VoidResponse, error)
}

func RegisterCertificatesServer(s *grpc.Server, srv CertificatesServer) {
	s.RegisterService(&_Certificates_serviceDesc, srv)
}

func _Certificates_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificatesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.certificate.v1beta1.Certificates/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificatesServer).List(ctx, req.(*CertificateListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Certificates_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificatesServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.certificate.v1beta1.Certificates/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificatesServer).Describe(ctx, req.(*CertificateDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Certificates_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateLoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificatesServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.certificate.v1beta1.Certificates/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificatesServer).Load(ctx, req.(*CertificateLoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Certificates_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificatesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.certificate.v1beta1.Certificates/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificatesServer).Delete(ctx, req.(*CertificateDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Certificates_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateDeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificatesServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.certificate.v1beta1.Certificates/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificatesServer).Deploy(ctx, req.(*CertificateDeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Certificates_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appscode.certificate.v1beta1.Certificates",
	HandlerType: (*CertificatesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Certificates_List_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _Certificates_Describe_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _Certificates_Load_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Certificates_Delete_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _Certificates_Deploy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "certificate.proto",
}

func init() { proto.RegisterFile("certificate.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 750 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x55, 0xcb, 0x6e, 0x13, 0x49,
	0x14, 0x55, 0xdb, 0x89, 0x1f, 0xd7, 0x1e, 0x29, 0x53, 0x8b, 0x49, 0x4f, 0x27, 0x99, 0x78, 0x7a,
	0x66, 0x61, 0x22, 0xd4, 0x4d, 0x42, 0x88, 0x20, 0x62, 0xe5, 0x58, 0x08, 0x04, 0x44, 0x91, 0x79,
	0x2c, 0xd8, 0x58, 0xe5, 0xee, 0x4a, 0x28, 0xd9, 0xee, 0x6a, 0xba, 0xca, 0x11, 0x2d, 0x94, 0x4d,
	0x3e, 0x80, 0x0d, 0x2b, 0x94, 0x25, 0x5b, 0x36, 0x20, 0xe5, 0x0b, 0xf8, 0x04, 0x7e, 0x81, 0x0f,
	0x41, 0x55, 0xd5, 0xb6, 0xcb, 0x79, 0xdb, 0x1b, 0xab, 0x7c, 0xce, 0xbd, 0x7d, 0xcf, 0x7d, 0x55,
	0xc1, 0x9f, 0x01, 0x49, 0x04, 0xdd, 0xa7, 0x01, 0x16, 0xc4, 0x8b, 0x13, 0x26, 0x18, 0x5a, 0xc6,
	0x71, 0xcc, 0x03, 0x16, 0x12, 0xcf, 0xe4, 0x0e, 0xd7, 0x3b, 0x44, 0xe0, 0x75, 0x67, 0xf9, 0x80,
	0xb1, 0x83, 0x1e, 0xf1, 0x71, 0x4c, 0x7d, 0x1c, 0x45, 0x4c, 0x60, 0x41, 0x59, 0xc4, 0xb5, 0xaf,
	0xf3, 0xcf, 0xd0, 0xf7, 0x12, 0x7e, 0x75, 0x82, 0x0f, 0x45, 0x1a, 0x13, 0xee, 0xab, 0x5f, 0x6d,
	0xe0, 0xda, 0xf0, 0xd7, 0xce, 0x38, 0xea, 0x33, 0xca, 0x45, 0x8b, 0xbc, 0x1b, 0x10, 0x2e, 0xdc,
	0xcf, 0x16, 0x2c, 0x9e, 0xa3, 0x78, 0xcc, 0x22, 0x4e, 0x90, 0x0f, 0x05, 0x2e, 0xb0, 0x18, 0x70,
	0xdb, 0xaa, 0x59, 0xf5, 0xca, 0xc6, 0xa2, 0x37, 0xca, 0x41, 0xc7, 0xf0, 0x5e, 0x28, 0xba, 0x95,
	0x99, 0xa1, 0xe7, 0x50, 0x35, 0x92, 0xe3, 0x76, 0xae, 0x96, 0xaf, 0x57, 0x36, 0x6e, 0x79, 0x57,
	0xa5, 0xee, 0x19, 0xd1, 0x5b, 0x13, 0xee, 0xae, 0x07, 0x8e, 0x41, 0x36, 0x09, 0x0f, 0x12, 0xda,
	0x21, 0x99, 0x72, 0xb4, 0x00, 0xf9, 0x01, 0x0d, 0x95, 0xb4, 0x72, 0x4b, 0x1e, 0xdd, 0x13, 0x0b,
	0x96, 0x2e, 0x74, 0x98, 0x35, 0x9f, 0xa7, 0x50, 0x31, 0x04, 0xd9, 0x39, 0xe5, 0x35, 0x45, 0x3a,
	0xa6, 0xb7, 0xfb, 0x35, 0x07, 0x15, 0x83, 0x44, 0x08, 0xe6, 0xe2, 0xb7, 0xa3, 0x04, 0xd4, 0x59,
	0x62, 0x11, 0xee, 0xeb, 0x48, 0xe5, 0x96, 0x3a, 0xa3, 0x55, 0xa8, 0x04, 0xac, 0xdf, 0x67, 0x51,
	0x5b, 0x51, 0x79, 0x45, 0x81, 0x86, 0x76, 0xa5, 0xc1, 0x12, 0x94, 0x29, 0xe7, 0x03, 0x12, 0xb6,
	0x3b, 0xa9, 0x3d, 0xa7, 0xe8, 0x92, 0x06, 0x1a, 0x29, 0x5a, 0x01, 0x38, 0xc4, 0x3d, 0x1a, 0xb6,
	0xf7, 0x13, 0xd6, 0xb7, 0xe7, 0x6b, 0x56, 0x3d, 0xdf, 0x2a, 0x2b, 0xe4, 0x51, 0xc2, 0xfa, 0xf2,
	0xe3, 0xe4, 0x7d, 0x4c, 0x13, 0xd2, 0x0e, 0x65, 0x86, 0x05, 0xc5, 0x83, 0x86, 0x9a, 0x99, 0x4a,
	0x8e, 0x23, 0x6e, 0x17, 0x6b, 0x79, 0xa9, 0x48, 0x9e, 0x25, 0x26, 0x13, 0xb3, 0x4b, 0x5a, 0xa5,
	0x3c, 0xcb, 0x6e, 0x74, 0x49, 0x6a, 0x97, 0x75, 0x37, 0xba, 0x24, 0x45, 0x36, 0x14, 0x0f, 0x49,
	0xc2, 0x29, 0x8b, 0x6c, 0xa8, 0x59, 0xf5, 0xf9, 0xd6, 0xf0, 0x2f, 0xfa, 0x0f, 0xfe, 0xe0, 0x24,
	0xa1, 0xb8, 0xd7, 0x8e, 0x06, 0xfd, 0x0e, 0x49, 0xec, 0x8a, 0xf2, 0xaa, 0x6a, 0x70, 0x57, 0x61,
	0x6e, 0x38, 0x39, 0xb2, 0x0c, 0x87, 0xc3, 0xc6, 0x0f, 0x8b, 0x64, 0x19, 0x45, 0x5a, 0x82, 0xb2,
	0x94, 0x21, 0xb3, 0xc0, 0x59, 0xf5, 0x4a, 0x12, 0x68, 0x62, 0x81, 0xd1, 0xdf, 0x50, 0xea, 0x92,
	0x54, 0x73, 0xba, 0x7c, 0xc5, 0x2e, 0x49, 0x25, 0xe5, 0xde, 0x06, 0x7b, 0x62, 0x62, 0x7a, 0x44,
	0x5c, 0x31, 0x60, 0x1f, 0xad, 0x33, 0xe6, 0x71, 0x8f, 0xa5, 0x97, 0x9a, 0xcb, 0xe2, 0x72, 0x12,
	0x24, 0x44, 0xb4, 0x8d, 0xa6, 0x82, 0x86, 0x54, 0xe7, 0xfe, 0x85, 0x6a, 0xd0, 0x1b, 0x70, 0x41,
	0x12, 0xb3, 0xb7, 0x95, 0x0c, 0x53, 0x26, 0xcb, 0x50, 0x96, 0x14, 0x8f, 0x71, 0x40, 0xb2, 0xe6,
	0x8e, 0x81, 0x8d, 0x93, 0x22, 0x54, 0x0d, 0x41, 0x1c, 0x7d, 0xb3, 0x60, 0x4e, 0xee, 0x30, 0xda,
	0xbc, 0xf1, 0x94, 0x1a, 0xb7, 0x81, 0x73, 0x6f, 0x4a, 0x2f, 0xbd, 0x58, 0xee, 0xc3, 0xe3, 0x53,
	0x3b, 0x57, 0xb2, 0x8e, 0x7f, 0xfe, 0xfa, 0x94, 0xbb, 0x83, 0x3c, 0x7f, 0xe2, 0x3a, 0x32, 0x3e,
	0xe4, 0x67, 0x1f, 0x32, 0x31, 0x8e, 0x7e, 0x58, 0x50, 0x1a, 0xee, 0x2a, 0xba, 0x7f, 0x63, 0x05,
	0x67, 0xee, 0x03, 0xe7, 0xc1, 0x0c, 0x9e, 0x99, 0xfe, 0x86, 0xa1, 0x7f, 0x0b, 0x6d, 0x4e, 0xa7,
	0xdf, 0xff, 0x30, 0xa0, 0xe1, 0x11, 0xfa, 0x2e, 0x2b, 0xcf, 0x70, 0x38, 0x4d, 0xe5, 0xc7, 0x43,
	0xed, 0xac, 0x9c, 0xbb, 0x8b, 0x5e, 0x33, 0x1a, 0x8e, 0x14, 0xbe, 0x32, 0x14, 0x3e, 0x71, 0x9a,
	0xd3, 0x2a, 0x94, 0x13, 0x73, 0xe4, 0xe3, 0x40, 0x3d, 0x1a, 0x3e, 0xeb, 0x08, 0x4c, 0xa3, 0x6d,
	0x6b, 0x0d, 0x7d, 0xb1, 0xa0, 0xa0, 0x87, 0x1e, 0x6d, 0x4d, 0x51, 0x3e, 0x63, 0x4b, 0xae, 0x13,
	0x3e, 0x51, 0xda, 0xb5, 0xd9, 0x4a, 0x7b, 0xaa, 0x54, 0xca, 0x5d, 0x9b, 0x4a, 0xa5, 0xb1, 0x9c,
	0xd7, 0xa9, 0x7c, 0x69, 0xa8, 0x7c, 0xec, 0xec, 0xcc, 0xa2, 0x72, 0x54, 0xdd, 0x50, 0x05, 0xde,
	0xb6, 0xd6, 0x1a, 0x3b, 0xf0, 0x7f, 0xc0, 0xfa, 0xe3, 0xc8, 0x38, 0xa6, 0x17, 0xa9, 0x6e, 0x2c,
	0x18, 0xb2, 0xf7, 0xe4, 0x7b, 0xbd, 0x67, 0xbd, 0x29, 0x66, 0x64, 0xa7, 0xa0, 0x5e, 0xf0, 0xbb,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x20, 0xaf, 0x6e, 0xba, 0x53, 0x08, 0x00, 0x00,
}
