// Code generated by protoc-gen-go.
// source: bucket.proto
// DO NOT EDIT!

/*
Package bucket is a generated protocol buffer package.

It is generated from these files:
	bucket.proto

It has these top-level messages:
	BucketListRequest
	BucketListResponse
*/
package bucket

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BucketListRequest struct {
	CloudCredential string `protobuf:"bytes,1,opt,name=cloud_credential,json=cloudCredential" json:"cloud_credential,omitempty"`
}

func (m *BucketListRequest) Reset()                    { *m = BucketListRequest{} }
func (m *BucketListRequest) String() string            { return proto.CompactTextString(m) }
func (*BucketListRequest) ProtoMessage()               {}
func (*BucketListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BucketListResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Name   []string       `protobuf:"bytes,2,rep,name=name" json:"name,omitempty"`
}

func (m *BucketListResponse) Reset()                    { *m = BucketListResponse{} }
func (m *BucketListResponse) String() string            { return proto.CompactTextString(m) }
func (*BucketListResponse) ProtoMessage()               {}
func (*BucketListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BucketListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*BucketListRequest)(nil), "bucket.BucketListRequest")
	proto.RegisterType((*BucketListResponse)(nil), "bucket.BucketListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Buckets service

type BucketsClient interface {
	List(ctx context.Context, in *BucketListRequest, opts ...grpc.CallOption) (*BucketListResponse, error)
}

type bucketsClient struct {
	cc *grpc.ClientConn
}

func NewBucketsClient(cc *grpc.ClientConn) BucketsClient {
	return &bucketsClient{cc}
}

func (c *bucketsClient) List(ctx context.Context, in *BucketListRequest, opts ...grpc.CallOption) (*BucketListResponse, error) {
	out := new(BucketListResponse)
	err := grpc.Invoke(ctx, "/bucket.Buckets/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Buckets service

type BucketsServer interface {
	List(context.Context, *BucketListRequest) (*BucketListResponse, error)
}

func RegisterBucketsServer(s *grpc.Server, srv BucketsServer) {
	s.RegisterService(&_Buckets_serviceDesc, srv)
}

func _Buckets_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bucket.Buckets/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketsServer).List(ctx, req.(*BucketListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Buckets_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bucket.Buckets",
	HandlerType: (*BucketsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Buckets_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("bucket.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2a, 0x4d, 0xce,
	0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0xa4, 0x64, 0xd2, 0xf3,
	0xf3, 0xd3, 0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12, 0x4b,
	0x32, 0xf3, 0xf3, 0x8a, 0x21, 0xaa, 0xa4, 0xc4, 0x40, 0xc2, 0x29, 0x25, 0x95, 0x05, 0xa9, 0xc5,
	0xfa, 0x60, 0x12, 0x22, 0xae, 0x64, 0xc7, 0x25, 0xe8, 0x04, 0xd6, 0xef, 0x93, 0x59, 0x5c, 0x12,
	0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0xa4, 0xc9, 0x25, 0x90, 0x9c, 0x93, 0x5f, 0x9a, 0x12,
	0x9f, 0x5c, 0x94, 0x9a, 0x92, 0x9a, 0x57, 0x92, 0x99, 0x98, 0x23, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x19, 0xc4, 0x0f, 0x16, 0x77, 0x86, 0x0b, 0x2b, 0x05, 0x70, 0x09, 0x21, 0xeb, 0x2f, 0x2e, 0x00,
	0x5a, 0x99, 0x2a, 0xa4, 0xc6, 0xc5, 0x56, 0x0c, 0xb4, 0xbf, 0xb4, 0x18, 0xac, 0x8d, 0xdb, 0x88,
	0x4f, 0x0f, 0x62, 0xb5, 0x5e, 0x30, 0x58, 0x34, 0x08, 0x2a, 0x2b, 0x24, 0xc4, 0xc5, 0x92, 0x97,
	0x98, 0x9b, 0x2a, 0xc1, 0xa4, 0xc0, 0x0c, 0x34, 0x1c, 0xcc, 0x36, 0xca, 0xe1, 0x62, 0x87, 0x98,
	0x58, 0x2c, 0x94, 0xc8, 0xc5, 0x02, 0x32, 0x56, 0x48, 0x52, 0x0f, 0xea, 0x63, 0x0c, 0xa7, 0x4a,
	0x49, 0x61, 0x93, 0x82, 0xb8, 0x42, 0x49, 0xa9, 0xe9, 0xf2, 0x93, 0xc9, 0x4c, 0x32, 0x42, 0x52,
	0xc0, 0x30, 0x29, 0x28, 0x4e, 0xce, 0x4f, 0x81, 0x04, 0x0e, 0x44, 0x43, 0xb1, 0x7e, 0x99, 0x81,
	0x9e, 0x61, 0x12, 0x1b, 0x38, 0x18, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x7c, 0xae,
	0xe5, 0x54, 0x01, 0x00, 0x00,
}
