// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package dtypes is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	ErrorDetails
	LongRunningResponse
	VoidRequest
	VoidResponse
	Uid
*/
package dtypes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Basic Error details message to send in response. Application specific
// error messages can be provided.
type ErrorDetails struct {
	Cause      string                   `protobuf:"bytes,1,opt,name=cause" json:"cause,omitempty"`
	StackTrace *ErrorDetails_StackTrace `protobuf:"bytes,2,opt,name=stack_trace,json=stackTrace" json:"stack_trace,omitempty"`
}

func (m *ErrorDetails) Reset()                    { *m = ErrorDetails{} }
func (m *ErrorDetails) String() string            { return proto.CompactTextString(m) }
func (*ErrorDetails) ProtoMessage()               {}
func (*ErrorDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ErrorDetails) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *ErrorDetails) GetStackTrace() *ErrorDetails_StackTrace {
	if m != nil {
		return m.StackTrace
	}
	return nil
}

type ErrorDetails_StackTrace struct {
	Frames []string `protobuf:"bytes,1,rep,name=frames" json:"frames,omitempty"`
}

func (m *ErrorDetails_StackTrace) Reset()                    { *m = ErrorDetails_StackTrace{} }
func (m *ErrorDetails_StackTrace) String() string            { return proto.CompactTextString(m) }
func (*ErrorDetails_StackTrace) ProtoMessage()               {}
func (*ErrorDetails_StackTrace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *ErrorDetails_StackTrace) GetFrames() []string {
	if m != nil {
		return m.Frames
	}
	return nil
}

// Types for long running operation. usually called as jobs.
// Next Id = 3
type LongRunningResponse struct {
	JobPhid string `protobuf:"bytes,1,opt,name=job_phid,json=jobPhid" json:"job_phid,omitempty"`
}

func (m *LongRunningResponse) Reset()                    { *m = LongRunningResponse{} }
func (m *LongRunningResponse) String() string            { return proto.CompactTextString(m) }
func (*LongRunningResponse) ProtoMessage()               {}
func (*LongRunningResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LongRunningResponse) GetJobPhid() string {
	if m != nil {
		return m.JobPhid
	}
	return ""
}

// Void Requests and response to use with other types.
type VoidRequest struct {
}

func (m *VoidRequest) Reset()                    { *m = VoidRequest{} }
func (m *VoidRequest) String() string            { return proto.CompactTextString(m) }
func (*VoidRequest) ProtoMessage()               {}
func (*VoidRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type VoidResponse struct {
}

func (m *VoidResponse) Reset()                    { *m = VoidResponse{} }
func (m *VoidResponse) String() string            { return proto.CompactTextString(m) }
func (*VoidResponse) ProtoMessage()               {}
func (*VoidResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// Response/Output only
type Uid struct {
	Phid string `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Uid) Reset()                    { *m = Uid{} }
func (m *Uid) String() string            { return proto.CompactTextString(m) }
func (*Uid) ProtoMessage()               {}
func (*Uid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Uid) GetPhid() string {
	if m != nil {
		return m.Phid
	}
	return ""
}

func (m *Uid) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ErrorDetails)(nil), "appscode.dtypes.ErrorDetails")
	proto.RegisterType((*ErrorDetails_StackTrace)(nil), "appscode.dtypes.ErrorDetails.StackTrace")
	proto.RegisterType((*LongRunningResponse)(nil), "appscode.dtypes.LongRunningResponse")
	proto.RegisterType((*VoidRequest)(nil), "appscode.dtypes.VoidRequest")
	proto.RegisterType((*VoidResponse)(nil), "appscode.dtypes.VoidResponse")
	proto.RegisterType((*Uid)(nil), "appscode.dtypes.Uid")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x54, 0x5e, 0x1f, 0x85, 0x6c, 0x0a, 0x48, 0x06, 0x41, 0xdb, 0x53, 0x15, 0x71, 0xc8, 0x85,
	0x14, 0xc1, 0x1f, 0x54, 0x70, 0x40, 0xe2, 0x50, 0x99, 0xc2, 0x81, 0x4b, 0xe5, 0xc4, 0xdb, 0xd4,
	0xa5, 0xf5, 0x1a, 0xdb, 0x39, 0xf4, 0x43, 0xf8, 0x5f, 0x94, 0xb8, 0xa2, 0x15, 0xb7, 0x99, 0xd9,
	0x1d, 0x7b, 0x67, 0x20, 0xf1, 0x5b, 0x83, 0x2e, 0x37, 0x96, 0x3c, 0xb1, 0x73, 0x61, 0x8c, 0x2b,
	0x49, 0x62, 0x2e, 0x5b, 0x79, 0x38, 0xa8, 0x88, 0xaa, 0x35, 0x8e, 0xdb, 0x71, 0x51, 0x2f, 0xc6,
	0x42, 0x6f, 0xc3, 0x6e, 0xfa, 0x1d, 0x41, 0xef, 0xc9, 0x5a, 0xb2, 0x8f, 0xe8, 0x85, 0x5a, 0x3b,
	0x76, 0x09, 0x47, 0xa5, 0xa8, 0x1d, 0xf6, 0xa3, 0x51, 0x94, 0xc5, 0x3c, 0x10, 0xf6, 0x0c, 0x89,
	0xf3, 0xa2, 0xfc, 0x9c, 0x7b, 0x2b, 0x4a, 0xec, 0xff, 0x1b, 0x45, 0x59, 0x72, 0x9f, 0xe5, 0x7f,
	0x3e, 0xca, 0x0f, 0x5f, 0xca, 0x5f, 0x1b, 0xc3, 0xac, 0xd9, 0xe7, 0xe0, 0x7e, 0xf1, 0xf0, 0x06,
	0x60, 0x3f, 0x61, 0x57, 0xd0, 0x5d, 0x58, 0xb1, 0x41, 0xd7, 0x8f, 0x46, 0x9d, 0x2c, 0xe6, 0x3b,
	0x96, 0xde, 0xc1, 0xc5, 0x0b, 0xe9, 0x8a, 0xd7, 0x5a, 0x2b, 0x5d, 0x71, 0x74, 0x86, 0xb4, 0x43,
	0x36, 0x80, 0x93, 0x15, 0x15, 0x73, 0xb3, 0x54, 0x72, 0x77, 0xe0, 0xf1, 0x8a, 0x8a, 0xe9, 0x52,
	0xc9, 0xf4, 0x14, 0x92, 0x77, 0x52, 0x92, 0xe3, 0x57, 0x8d, 0xce, 0xa7, 0x67, 0xd0, 0x0b, 0x34,
	0x38, 0xd3, 0x5b, 0xe8, 0xbc, 0x29, 0xc9, 0x18, 0xfc, 0x3f, 0x30, 0xb7, 0xb8, 0xd1, 0xb4, 0xd8,
	0x84, 0x54, 0x31, 0x6f, 0xf1, 0x24, 0x87, 0xeb, 0x92, 0x36, 0xfb, 0x80, 0xc2, 0xa8, 0x5d, 0xc8,
	0x49, 0x3c, 0xdb, 0x1a, 0x9c, 0x36, 0xed, 0x4d, 0xa3, 0x8f, 0x6e, 0x10, 0x8b, 0x6e, 0x5b, 0xe7,
	0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0xd6, 0x12, 0xf9, 0x89, 0x01, 0x00, 0x00,
}
