// Code generated by protoc-gen-grpc-js-client
// source: server.proto
// DO NOT EDIT!

/*
This is a RSVP based Ajax client for gRPC gateway JSON APIs.
*/

var xhr = require('grpc-xhr');

function serversCreate(p, conf) {
    path = '/kubernetes/v1beta1/clusters/' + p['cluster'] + '/apps/bacula'
    delete p['cluster']
    return xhr(path, 'POST', conf, null, p);
}

function serversDelete(p, conf) {
    path = '/kubernetes/v1beta1/clusters/' + p['cluster'] + '/apps/bacula'
    delete p['cluster']
    return xhr(path, 'DELETE', conf, p);
}

var services = {
    servers: {
        create: serversCreate,
        delete: serversDelete
    }
};

module.exports = {backup: {v1beta1: services}};
