// Code generated by protoc-gen-go.
// source: conduit.proto
// DO NOT EDIT!

package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ConduitRequest struct {
}

func (m *ConduitRequest) Reset()                    { *m = ConduitRequest{} }
func (m *ConduitRequest) String() string            { return proto.CompactTextString(m) }
func (*ConduitRequest) ProtoMessage()               {}
func (*ConduitRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type ConduitWhoAmIResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	User   *ConduitUser   `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *ConduitWhoAmIResponse) Reset()                    { *m = ConduitWhoAmIResponse{} }
func (m *ConduitWhoAmIResponse) String() string            { return proto.CompactTextString(m) }
func (*ConduitWhoAmIResponse) ProtoMessage()               {}
func (*ConduitWhoAmIResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ConduitWhoAmIResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ConduitWhoAmIResponse) GetUser() *ConduitUser {
	if m != nil {
		return m.User
	}
	return nil
}

type ConduitUsersResponse struct {
	Status *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	User   []*ConduitUser `protobuf:"bytes,2,rep,name=user" json:"user,omitempty"`
}

func (m *ConduitUsersResponse) Reset()                    { *m = ConduitUsersResponse{} }
func (m *ConduitUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*ConduitUsersResponse) ProtoMessage()               {}
func (*ConduitUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ConduitUsersResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ConduitUsersResponse) GetUser() []*ConduitUser {
	if m != nil {
		return m.User
	}
	return nil
}

type ConduitUser struct {
	Phid         string   `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	UserName     string   `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	RealName     string   `protobuf:"bytes,3,opt,name=real_name,json=realName" json:"real_name,omitempty"`
	Image        string   `protobuf:"bytes,4,opt,name=image" json:"image,omitempty"`
	Uri          string   `protobuf:"bytes,5,opt,name=uri" json:"uri,omitempty"`
	Roles        []string `protobuf:"bytes,6,rep,name=roles" json:"roles,omitempty"`
	PrimaryEmail string   `protobuf:"bytes,7,opt,name=primary_email,json=primaryEmail" json:"primary_email,omitempty"`
}

func (m *ConduitUser) Reset()                    { *m = ConduitUser{} }
func (m *ConduitUser) String() string            { return proto.CompactTextString(m) }
func (*ConduitUser) ProtoMessage()               {}
func (*ConduitUser) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func init() {
	proto.RegisterType((*ConduitRequest)(nil), "auth.ConduitRequest")
	proto.RegisterType((*ConduitWhoAmIResponse)(nil), "auth.ConduitWhoAmIResponse")
	proto.RegisterType((*ConduitUsersResponse)(nil), "auth.ConduitUsersResponse")
	proto.RegisterType((*ConduitUser)(nil), "auth.ConduitUser")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Conduit service

type ConduitClient interface {
	// This rpc is used to check a valid user from other applications.
	WhoAmI(ctx context.Context, in *ConduitRequest, opts ...grpc.CallOption) (*ConduitWhoAmIResponse, error)
	// appctl used this to validates the user token with phabricator.
	Users(ctx context.Context, in *ConduitRequest, opts ...grpc.CallOption) (*ConduitUsersResponse, error)
}

type conduitClient struct {
	cc *grpc.ClientConn
}

func NewConduitClient(cc *grpc.ClientConn) ConduitClient {
	return &conduitClient{cc}
}

func (c *conduitClient) WhoAmI(ctx context.Context, in *ConduitRequest, opts ...grpc.CallOption) (*ConduitWhoAmIResponse, error) {
	out := new(ConduitWhoAmIResponse)
	err := grpc.Invoke(ctx, "/auth.Conduit/WhoAmI", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conduitClient) Users(ctx context.Context, in *ConduitRequest, opts ...grpc.CallOption) (*ConduitUsersResponse, error) {
	out := new(ConduitUsersResponse)
	err := grpc.Invoke(ctx, "/auth.Conduit/Users", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Conduit service

type ConduitServer interface {
	// This rpc is used to check a valid user from other applications.
	WhoAmI(context.Context, *ConduitRequest) (*ConduitWhoAmIResponse, error)
	// appctl used this to validates the user token with phabricator.
	Users(context.Context, *ConduitRequest) (*ConduitUsersResponse, error)
}

func RegisterConduitServer(s *grpc.Server, srv ConduitServer) {
	s.RegisterService(&_Conduit_serviceDesc, srv)
}

func _Conduit_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConduitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Conduit/WhoAmI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitServer).WhoAmI(ctx, req.(*ConduitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conduit_Users_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConduitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConduitServer).Users(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Conduit/Users",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConduitServer).Users(ctx, req.(*ConduitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Conduit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Conduit",
	HandlerType: (*ConduitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WhoAmI",
			Handler:    _Conduit_WhoAmI_Handler,
		},
		{
			MethodName: "Users",
			Handler:    _Conduit_Users_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

func init() { proto.RegisterFile("conduit.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0x4e, 0xe3, 0x30,
	0x14, 0xc6, 0x95, 0x26, 0x4d, 0xa7, 0xee, 0xb4, 0xea, 0x58, 0x9d, 0x51, 0x94, 0xce, 0xa2, 0xca,
	0xa8, 0xd5, 0xa8, 0x23, 0x25, 0x6d, 0x67, 0xd7, 0x1d, 0x42, 0x2c, 0xd8, 0xb0, 0x08, 0x42, 0x2c,
	0x2b, 0xd3, 0x98, 0xc6, 0x22, 0x89, 0x8d, 0xed, 0x80, 0xba, 0xe5, 0x0a, 0xdc, 0x87, 0x4b, 0x70,
	0x05, 0xc4, 0x39, 0x90, 0xff, 0x08, 0xb5, 0x42, 0xc0, 0x82, 0x4d, 0x64, 0xff, 0xbe, 0x97, 0xf7,
	0xd9, 0xfe, 0x1e, 0xe8, 0xae, 0x69, 0x95, 0xd5, 0x44, 0xc6, 0x8c, 0x53, 0x49, 0xa1, 0x87, 0x6a,
	0x99, 0x87, 0xbf, 0x37, 0x94, 0x6e, 0x0a, 0x9c, 0x20, 0x46, 0x12, 0x54, 0x55, 0x54, 0x22, 0x49,
	0x68, 0x25, 0x4c, 0x4d, 0xf8, 0x4b, 0xe1, 0x4c, 0x6e, 0x19, 0x16, 0x89, 0xfe, 0x1a, 0x1e, 0xf5,
	0x41, 0xef, 0xd0, 0x34, 0x4b, 0xf1, 0x75, 0x8d, 0x85, 0x8c, 0x2e, 0xc1, 0x4f, 0x4b, 0xce, 0x73,
	0x7a, 0x50, 0x1e, 0xa7, 0x58, 0x30, 0x5a, 0x09, 0x0c, 0x27, 0xc0, 0x17, 0x12, 0xc9, 0x5a, 0x04,
	0xce, 0xc8, 0xf9, 0xdb, 0x59, 0xf4, 0x62, 0xd3, 0x2f, 0x3e, 0xd5, 0x34, 0xb5, 0x2a, 0x1c, 0x03,
	0xaf, 0x16, 0x98, 0x07, 0x0d, 0x5d, 0xf5, 0x23, 0x56, 0xa7, 0x8b, 0x6d, 0xcb, 0x33, 0x81, 0x79,
	0xaa, 0xe5, 0x08, 0x83, 0xc1, 0x0e, 0x14, 0x5f, 0xb0, 0x71, 0x3f, 0xb2, 0x79, 0x70, 0x40, 0x67,
	0x87, 0x42, 0x08, 0x3c, 0x96, 0x93, 0x4c, 0x37, 0x6f, 0xa7, 0x7a, 0x0d, 0x87, 0xa0, 0xad, 0x6a,
	0x57, 0x15, 0x2a, 0xb1, 0x3e, 0x76, 0x3b, 0xfd, 0xa6, 0xc0, 0x09, 0x2a, 0xb1, 0x12, 0x39, 0x46,
	0x85, 0x11, 0x5d, 0x23, 0x2a, 0xa0, 0xc5, 0x01, 0x68, 0x92, 0x12, 0x6d, 0x70, 0xe0, 0x69, 0xc1,
	0x6c, 0x60, 0x1f, 0xb8, 0x35, 0x27, 0x41, 0x53, 0x33, 0xb5, 0x54, 0x75, 0x9c, 0x16, 0x58, 0x04,
	0xfe, 0xc8, 0x55, 0x75, 0x7a, 0x03, 0xff, 0x80, 0x2e, 0xe3, 0xa4, 0x44, 0x7c, 0xbb, 0xc2, 0x25,
	0x22, 0x45, 0xd0, 0xd2, 0x7f, 0x7c, 0xb7, 0xf0, 0x48, 0xb1, 0xc5, 0xb3, 0x03, 0x5a, 0xf6, 0x02,
	0xb0, 0x02, 0xbe, 0x09, 0x05, 0x0e, 0xf6, 0xee, 0x6b, 0xb3, 0x0b, 0x87, 0x7b, 0x74, 0x3f, 0xbf,
	0x68, 0x7e, 0xf7, 0xf8, 0x74, 0xdf, 0xf8, 0x17, 0x4d, 0x12, 0xc4, 0x98, 0x58, 0xd3, 0xcc, 0xce,
	0x4a, 0x2d, 0xf3, 0xe4, 0x66, 0x16, 0xcf, 0x13, 0x3b, 0x55, 0xc9, 0x6d, 0x4e, 0x51, 0x49, 0x96,
	0xce, 0x14, 0x5e, 0x81, 0xa6, 0x0e, 0xe7, 0x1d, 0xbb, 0xf0, 0xcd, 0xa3, 0xbf, 0xc6, 0x18, 0xcd,
	0xb4, 0xdb, 0x34, 0x1a, 0x7f, 0xe6, 0xa6, 0x1e, 0x5a, 0x2c, 0x9d, 0xe9, 0x85, 0xaf, 0x27, 0xf2,
	0xff, 0x4b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xa2, 0xc8, 0x42, 0xde, 0x02, 0x00, 0x00,
}
