// Code generated by protoc-gen-go.
// source: clusters.proto
// DO NOT EDIT!

package kubernetes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ClusterSettings struct {
	LogIndexPrefix string `protobuf:"bytes,1,opt,name=log_index_prefix,json=logIndexPrefix" json:"log_index_prefix,omitempty"`
	// Number of secs logs will be stored in ElasticSearch
	LogStorageLifetime int64 `protobuf:"varint,2,opt,name=log_storage_lifetime,json=logStorageLifetime" json:"log_storage_lifetime,omitempty"`
	// Number of secs logs will be stored in InfluxDB
	MonitoringStorageLifetime int64 `protobuf:"varint,3,opt,name=monitoring_storage_lifetime,json=monitoringStorageLifetime" json:"monitoring_storage_lifetime,omitempty"`
}

func (m *ClusterSettings) Reset()                    { *m = ClusterSettings{} }
func (m *ClusterSettings) String() string            { return proto.CompactTextString(m) }
func (*ClusterSettings) ProtoMessage()               {}
func (*ClusterSettings) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type Cluster struct {
	Phid                 string            `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Provider             string            `protobuf:"bytes,3,opt,name=provider" json:"provider,omitempty"`
	Os                   string            `protobuf:"bytes,4,opt,name=os" json:"os,omitempty"`
	Region               string            `protobuf:"bytes,5,opt,name=region" json:"region,omitempty"`
	Zone                 string            `protobuf:"bytes,6,opt,name=zone" json:"zone,omitempty"`
	CreatedAt            string            `protobuf:"bytes,7,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Links                map[string]string `protobuf:"bytes,8,rep,name=links" json:"links,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DoNotDelete          bool              `protobuf:"varint,9,opt,name=do_not_delete,json=doNotDelete" json:"do_not_delete,omitempty"`
	Status               string            `protobuf:"bytes,10,opt,name=status" json:"status,omitempty"`
	StatusCause          string            `protobuf:"bytes,11,opt,name=status_cause,json=statusCause" json:"status_cause,omitempty"`
	GceProject           string            `protobuf:"bytes,12,opt,name=gce_project,json=gceProject" json:"gce_project,omitempty"`
	KubeServerVersion    string            `protobuf:"bytes,13,opt,name=kube_server_version,json=kubeServerVersion" json:"kube_server_version,omitempty"`
	KubeSaltbaseVersion  string            `protobuf:"bytes,14,opt,name=kube_saltbase_version,json=kubeSaltbaseVersion" json:"kube_saltbase_version,omitempty"`
	KubeStarterVersion   string            `protobuf:"bytes,15,opt,name=kube_starter_version,json=kubeStarterVersion" json:"kube_starter_version,omitempty"`
	NodeCount            int32             `protobuf:"varint,16,opt,name=node_count,json=nodeCount" json:"node_count,omitempty"`
	ApiServerUrl         string            `protobuf:"bytes,17,opt,name=api_server_url,json=apiServerUrl" json:"api_server_url,omitempty"`
	KubeUser             string            `protobuf:"bytes,18,opt,name=kube_user,json=kubeUser" json:"kube_user,omitempty"`
	KubePassword         string            `protobuf:"bytes,19,opt,name=kube_password,json=kubePassword" json:"kube_password,omitempty"`
	CaCert               string            `protobuf:"bytes,20,opt,name=ca_cert,json=caCert" json:"ca_cert,omitempty"`
	KubeBearerToken      string            `protobuf:"bytes,21,opt,name=kube_bearer_token,json=kubeBearerToken" json:"kube_bearer_token,omitempty"`
	Settings             *ClusterSettings  `protobuf:"bytes,22,opt,name=settings" json:"settings,omitempty"`
	InstanceRootPassword string            `protobuf:"bytes,23,opt,name=instance_root_password,json=instanceRootPassword" json:"instance_root_password,omitempty"`
	Version              string            `protobuf:"bytes,24,opt,name=version" json:"version,omitempty"`
	Sku                  string            `protobuf:"bytes,25,opt,name=sku" json:"sku,omitempty"`
	CreatedBy            string            `protobuf:"bytes,26,opt,name=created_by,json=createdBy" json:"created_by,omitempty"`
}

func (m *Cluster) Reset()                    { *m = Cluster{} }
func (m *Cluster) String() string            { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()               {}
func (*Cluster) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Cluster) GetLinks() map[string]string {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Cluster) GetSettings() *ClusterSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type ClusterDescribeRequest struct {
	Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *ClusterDescribeRequest) Reset()                    { *m = ClusterDescribeRequest{} }
func (m *ClusterDescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterDescribeRequest) ProtoMessage()               {}
func (*ClusterDescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type ClusterDescribeResponse struct {
	Status  *dtypes.Status                `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Cluster *Cluster                      `protobuf:"bytes,2,opt,name=cluster" json:"cluster,omitempty"`
	Spec    *ClusterDescribeResponse_Spec `protobuf:"bytes,3,opt,name=spec" json:"spec,omitempty"`
}

func (m *ClusterDescribeResponse) Reset()                    { *m = ClusterDescribeResponse{} }
func (m *ClusterDescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterDescribeResponse) ProtoMessage()               {}
func (*ClusterDescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ClusterDescribeResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ClusterDescribeResponse) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *ClusterDescribeResponse) GetSpec() *ClusterDescribeResponse_Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type ClusterDescribeResponse_Spec struct {
	ContainerCount int32 `protobuf:"varint,1,opt,name=container_count,json=containerCount" json:"container_count,omitempty"`
	PodCount       int32 `protobuf:"varint,2,opt,name=pod_count,json=podCount" json:"pod_count,omitempty"`
	ServiceCount   int32 `protobuf:"varint,3,opt,name=service_count,json=serviceCount" json:"service_count,omitempty"`
	RcCount        int32 `protobuf:"varint,4,opt,name=rc_count,json=rcCount" json:"rc_count,omitempty"`
	TotalCpu       int64 `protobuf:"varint,5,opt,name=total_cpu,json=totalCpu" json:"total_cpu,omitempty"`
	TotalMemory    int64 `protobuf:"varint,6,opt,name=total_memory,json=totalMemory" json:"total_memory,omitempty"`
}

func (m *ClusterDescribeResponse_Spec) Reset()                    { *m = ClusterDescribeResponse_Spec{} }
func (m *ClusterDescribeResponse_Spec) String() string            { return proto.CompactTextString(m) }
func (*ClusterDescribeResponse_Spec) ProtoMessage()               {}
func (*ClusterDescribeResponse_Spec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 0} }

type ClusterListRequest struct {
	Status []string `protobuf:"bytes,1,rep,name=status" json:"status,omitempty"`
}

func (m *ClusterListRequest) Reset()                    { *m = ClusterListRequest{} }
func (m *ClusterListRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterListRequest) ProtoMessage()               {}
func (*ClusterListRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type ClusterListResponse struct {
	Status   *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Clusters []*Cluster     `protobuf:"bytes,2,rep,name=clusters" json:"clusters,omitempty"`
}

func (m *ClusterListResponse) Reset()                    { *m = ClusterListResponse{} }
func (m *ClusterListResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterListResponse) ProtoMessage()               {}
func (*ClusterListResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ClusterListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ClusterListResponse) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

type ClusterCreateRequest struct {
	Name                string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Provider            string            `protobuf:"bytes,2,opt,name=provider" json:"provider,omitempty"`
	Zone                string            `protobuf:"bytes,3,opt,name=zone" json:"zone,omitempty"`
	CloudCredential     string            `protobuf:"bytes,4,opt,name=cloud_credential,json=cloudCredential" json:"cloud_credential,omitempty"`
	CloudCredentialData map[string]string `protobuf:"bytes,5,rep,name=cloud_credential_data,json=cloudCredentialData" json:"cloud_credential_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NodeSet             map[string]int64  `protobuf:"bytes,6,rep,name=node_set,json=nodeSet" json:"node_set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	KubeSaltbaseVersion string            `protobuf:"bytes,7,opt,name=kube_saltbase_version,json=kubeSaltbaseVersion" json:"kube_saltbase_version,omitempty"`
	KubeStarterVersion  string            `protobuf:"bytes,8,opt,name=kube_starter_version,json=kubeStarterVersion" json:"kube_starter_version,omitempty"`
	KubeServerVersion   string            `protobuf:"bytes,9,opt,name=kube_server_version,json=kubeServerVersion" json:"kube_server_version,omitempty"`
	DoNotDelete         bool              `protobuf:"varint,10,opt,name=do_not_delete,json=doNotDelete" json:"do_not_delete,omitempty"`
	HostfactsVersion    string            `protobuf:"bytes,11,opt,name=hostfacts_version,json=hostfactsVersion" json:"hostfacts_version,omitempty"`
	Version             string            `protobuf:"bytes,12,opt,name=version" json:"version,omitempty"`
}

func (m *ClusterCreateRequest) Reset()                    { *m = ClusterCreateRequest{} }
func (m *ClusterCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterCreateRequest) ProtoMessage()               {}
func (*ClusterCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *ClusterCreateRequest) GetCloudCredentialData() map[string]string {
	if m != nil {
		return m.CloudCredentialData
	}
	return nil
}

func (m *ClusterCreateRequest) GetNodeSet() map[string]int64 {
	if m != nil {
		return m.NodeSet
	}
	return nil
}

type ClusterScaleRequest struct {
	Name        string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	NodeChanges map[string]int64 `protobuf:"bytes,2,rep,name=node_changes,json=nodeChanges" json:"node_changes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *ClusterScaleRequest) Reset()                    { *m = ClusterScaleRequest{} }
func (m *ClusterScaleRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterScaleRequest) ProtoMessage()               {}
func (*ClusterScaleRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ClusterScaleRequest) GetNodeChanges() map[string]int64 {
	if m != nil {
		return m.NodeChanges
	}
	return nil
}

type ClusterDeleteRequest struct {
	Name              string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ReleaseReservedIp bool   `protobuf:"varint,2,opt,name=release_reserved_ip,json=releaseReservedIp" json:"release_reserved_ip,omitempty"`
	Force             bool   `protobuf:"varint,3,opt,name=force" json:"force,omitempty"`
}

func (m *ClusterDeleteRequest) Reset()                    { *m = ClusterDeleteRequest{} }
func (m *ClusterDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterDeleteRequest) ProtoMessage()               {}
func (*ClusterDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

type ClusterStartupScriptRequest struct {
	Uid  string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Role string `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
}

func (m *ClusterStartupScriptRequest) Reset()                    { *m = ClusterStartupScriptRequest{} }
func (m *ClusterStartupScriptRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterStartupScriptRequest) ProtoMessage()               {}
func (*ClusterStartupScriptRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

type ClusterStartupScriptResponse struct {
	Status        *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Configuration string         `protobuf:"bytes,2,opt,name=configuration" json:"configuration,omitempty"`
}

func (m *ClusterStartupScriptResponse) Reset()                    { *m = ClusterStartupScriptResponse{} }
func (m *ClusterStartupScriptResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterStartupScriptResponse) ProtoMessage()               {}
func (*ClusterStartupScriptResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *ClusterStartupScriptResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ClusterInstanceByIPRequest struct {
	Phid       string `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	ExternalIp string `protobuf:"bytes,2,opt,name=external_ip,json=externalIp" json:"external_ip,omitempty"`
}

func (m *ClusterInstanceByIPRequest) Reset()                    { *m = ClusterInstanceByIPRequest{} }
func (m *ClusterInstanceByIPRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterInstanceByIPRequest) ProtoMessage()               {}
func (*ClusterInstanceByIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

type ClusterInstanceResponse struct {
	Status   *dtypes.Status   `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Instance *ClusterInstance `protobuf:"bytes,2,opt,name=instance" json:"instance,omitempty"`
}

func (m *ClusterInstanceResponse) Reset()                    { *m = ClusterInstanceResponse{} }
func (m *ClusterInstanceResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterInstanceResponse) ProtoMessage()               {}
func (*ClusterInstanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *ClusterInstanceResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ClusterInstanceResponse) GetInstance() *ClusterInstance {
	if m != nil {
		return m.Instance
	}
	return nil
}

type ClusterClientConfigRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ClusterClientConfigRequest) Reset()                    { *m = ClusterClientConfigRequest{} }
func (m *ClusterClientConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterClientConfigRequest) ProtoMessage()               {}
func (*ClusterClientConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

type ClusterClientConfigResponse struct {
	Status          *dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Configuration   string         `protobuf:"bytes,2,opt,name=configuration" json:"configuration,omitempty"`
	ClusterDomain   string         `protobuf:"bytes,3,opt,name=cluster_domain,json=clusterDomain" json:"cluster_domain,omitempty"`
	CaCert          string         `protobuf:"bytes,4,opt,name=ca_cert,json=caCert" json:"ca_cert,omitempty"`
	ApiServerUrl    string         `protobuf:"bytes,5,opt,name=api_server_url,json=apiServerUrl" json:"api_server_url,omitempty"`
	ClusterUserName string         `protobuf:"bytes,6,opt,name=cluster_user_name,json=clusterUserName" json:"cluster_user_name,omitempty"`
	UserCert        string         `protobuf:"bytes,7,opt,name=user_cert,json=userCert" json:"user_cert,omitempty"`
	UserKey         string         `protobuf:"bytes,8,opt,name=user_key,json=userKey" json:"user_key,omitempty"`
	ContextName     string         `protobuf:"bytes,9,opt,name=context_name,json=contextName" json:"context_name,omitempty"`
	UserToken       string         `protobuf:"bytes,10,opt,name=user_token,json=userToken" json:"user_token,omitempty"`
}

func (m *ClusterClientConfigResponse) Reset()                    { *m = ClusterClientConfigResponse{} }
func (m *ClusterClientConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterClientConfigResponse) ProtoMessage()               {}
func (*ClusterClientConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *ClusterClientConfigResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ClusterClientContainerRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DiskName string `protobuf:"bytes,2,opt,name=disk_name,json=diskName" json:"disk_name,omitempty"`
}

func (m *ClusterClientContainerRequest) Reset()                    { *m = ClusterClientContainerRequest{} }
func (m *ClusterClientContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterClientContainerRequest) ProtoMessage()               {}
func (*ClusterClientContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

type ClusterInstanceListRequest struct {
	ClusterName string `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName" json:"cluster_name,omitempty"`
}

func (m *ClusterInstanceListRequest) Reset()                    { *m = ClusterInstanceListRequest{} }
func (m *ClusterInstanceListRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterInstanceListRequest) ProtoMessage()               {}
func (*ClusterInstanceListRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

type ClusterInstance struct {
	Phid       string `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	ExternalId string `protobuf:"bytes,2,opt,name=external_id,json=externalId" json:"external_id,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ExternalIp string `protobuf:"bytes,4,opt,name=external_ip,json=externalIp" json:"external_ip,omitempty"`
	InternalIp string `protobuf:"bytes,5,opt,name=internal_ip,json=internalIp" json:"internal_ip,omitempty"`
	Sku        string `protobuf:"bytes,6,opt,name=sku" json:"sku,omitempty"`
}

func (m *ClusterInstance) Reset()                    { *m = ClusterInstance{} }
func (m *ClusterInstance) String() string            { return proto.CompactTextString(m) }
func (*ClusterInstance) ProtoMessage()               {}
func (*ClusterInstance) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

type ClusterInstanceListResponse struct {
	Status    *dtypes.Status     `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Instances []*ClusterInstance `protobuf:"bytes,2,rep,name=instances" json:"instances,omitempty"`
}

func (m *ClusterInstanceListResponse) Reset()                    { *m = ClusterInstanceListResponse{} }
func (m *ClusterInstanceListResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterInstanceListResponse) ProtoMessage()               {}
func (*ClusterInstanceListResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *ClusterInstanceListResponse) GetStatus() *dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ClusterInstanceListResponse) GetInstances() []*ClusterInstance {
	if m != nil {
		return m.Instances
	}
	return nil
}

type ClusterUpdateRequest struct {
	Name        string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DoNotDelete bool             `protobuf:"varint,2,opt,name=do_not_delete,json=doNotDelete" json:"do_not_delete,omitempty"`
	Settings    *ClusterSettings `protobuf:"bytes,3,opt,name=settings" json:"settings,omitempty"`
}

func (m *ClusterUpdateRequest) Reset()                    { *m = ClusterUpdateRequest{} }
func (m *ClusterUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterUpdateRequest) ProtoMessage()               {}
func (*ClusterUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *ClusterUpdateRequest) GetSettings() *ClusterSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type ClusterUpgradeRequest struct {
	Name                string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	KubeSaltbaseVersion string `protobuf:"bytes,2,opt,name=kube_saltbase_version,json=kubeSaltbaseVersion" json:"kube_saltbase_version,omitempty"`
	KubeStarterVersion  string `protobuf:"bytes,3,opt,name=kube_starter_version,json=kubeStarterVersion" json:"kube_starter_version,omitempty"`
	KubeServerVersion   string `protobuf:"bytes,4,opt,name=kube_server_version,json=kubeServerVersion" json:"kube_server_version,omitempty"`
	HostfactsVersion    string `protobuf:"bytes,5,opt,name=hostfacts_version,json=hostfactsVersion" json:"hostfacts_version,omitempty"`
	Version             string `protobuf:"bytes,6,opt,name=version" json:"version,omitempty"`
}

func (m *ClusterUpgradeRequest) Reset()                    { *m = ClusterUpgradeRequest{} }
func (m *ClusterUpgradeRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterUpgradeRequest) ProtoMessage()               {}
func (*ClusterUpgradeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func init() {
	proto.RegisterType((*ClusterSettings)(nil), "kubernetes.ClusterSettings")
	proto.RegisterType((*Cluster)(nil), "kubernetes.Cluster")
	proto.RegisterType((*ClusterDescribeRequest)(nil), "kubernetes.ClusterDescribeRequest")
	proto.RegisterType((*ClusterDescribeResponse)(nil), "kubernetes.ClusterDescribeResponse")
	proto.RegisterType((*ClusterDescribeResponse_Spec)(nil), "kubernetes.ClusterDescribeResponse.Spec")
	proto.RegisterType((*ClusterListRequest)(nil), "kubernetes.ClusterListRequest")
	proto.RegisterType((*ClusterListResponse)(nil), "kubernetes.ClusterListResponse")
	proto.RegisterType((*ClusterCreateRequest)(nil), "kubernetes.ClusterCreateRequest")
	proto.RegisterType((*ClusterScaleRequest)(nil), "kubernetes.ClusterScaleRequest")
	proto.RegisterType((*ClusterDeleteRequest)(nil), "kubernetes.ClusterDeleteRequest")
	proto.RegisterType((*ClusterStartupScriptRequest)(nil), "kubernetes.ClusterStartupScriptRequest")
	proto.RegisterType((*ClusterStartupScriptResponse)(nil), "kubernetes.ClusterStartupScriptResponse")
	proto.RegisterType((*ClusterInstanceByIPRequest)(nil), "kubernetes.ClusterInstanceByIPRequest")
	proto.RegisterType((*ClusterInstanceResponse)(nil), "kubernetes.ClusterInstanceResponse")
	proto.RegisterType((*ClusterClientConfigRequest)(nil), "kubernetes.ClusterClientConfigRequest")
	proto.RegisterType((*ClusterClientConfigResponse)(nil), "kubernetes.ClusterClientConfigResponse")
	proto.RegisterType((*ClusterClientContainerRequest)(nil), "kubernetes.ClusterClientContainerRequest")
	proto.RegisterType((*ClusterInstanceListRequest)(nil), "kubernetes.ClusterInstanceListRequest")
	proto.RegisterType((*ClusterInstance)(nil), "kubernetes.ClusterInstance")
	proto.RegisterType((*ClusterInstanceListResponse)(nil), "kubernetes.ClusterInstanceListResponse")
	proto.RegisterType((*ClusterUpdateRequest)(nil), "kubernetes.ClusterUpdateRequest")
	proto.RegisterType((*ClusterUpgradeRequest)(nil), "kubernetes.ClusterUpgradeRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Clusters service

type ClustersClient interface {
	List(ctx context.Context, in *ClusterListRequest, opts ...grpc.CallOption) (*ClusterListResponse, error)
	Describe(ctx context.Context, in *ClusterDescribeRequest, opts ...grpc.CallOption) (*ClusterDescribeResponse, error)
	Create(ctx context.Context, in *ClusterCreateRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error)
	Update(ctx context.Context, in *ClusterUpdateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error)
	Scale(ctx context.Context, in *ClusterScaleRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error)
	Upgrade(ctx context.Context, in *ClusterUpgradeRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error)
	Delete(ctx context.Context, in *ClusterDeleteRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error)
	ClientConfig(ctx context.Context, in *ClusterClientConfigRequest, opts ...grpc.CallOption) (*ClusterClientConfigResponse, error)
	Instances(ctx context.Context, in *ClusterInstanceListRequest, opts ...grpc.CallOption) (*ClusterInstanceListResponse, error)
	StartupScript(ctx context.Context, in *ClusterStartupScriptRequest, opts ...grpc.CallOption) (*ClusterStartupScriptResponse, error)
	InstanceByIP(ctx context.Context, in *ClusterInstanceByIPRequest, opts ...grpc.CallOption) (*ClusterInstanceResponse, error)
}

type clustersClient struct {
	cc *grpc.ClientConn
}

func NewClustersClient(cc *grpc.ClientConn) ClustersClient {
	return &clustersClient{cc}
}

func (c *clustersClient) List(ctx context.Context, in *ClusterListRequest, opts ...grpc.CallOption) (*ClusterListResponse, error) {
	out := new(ClusterListResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Describe(ctx context.Context, in *ClusterDescribeRequest, opts ...grpc.CallOption) (*ClusterDescribeResponse, error) {
	out := new(ClusterDescribeResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Create(ctx context.Context, in *ClusterCreateRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error) {
	out := new(dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Update(ctx context.Context, in *ClusterUpdateRequest, opts ...grpc.CallOption) (*dtypes.VoidResponse, error) {
	out := new(dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Scale(ctx context.Context, in *ClusterScaleRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error) {
	out := new(dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/Scale", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Upgrade(ctx context.Context, in *ClusterUpgradeRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error) {
	out := new(dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/Upgrade", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Delete(ctx context.Context, in *ClusterDeleteRequest, opts ...grpc.CallOption) (*dtypes.LongRunningResponse, error) {
	out := new(dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) ClientConfig(ctx context.Context, in *ClusterClientConfigRequest, opts ...grpc.CallOption) (*ClusterClientConfigResponse, error) {
	out := new(ClusterClientConfigResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/ClientConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Instances(ctx context.Context, in *ClusterInstanceListRequest, opts ...grpc.CallOption) (*ClusterInstanceListResponse, error) {
	out := new(ClusterInstanceListResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/Instances", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) StartupScript(ctx context.Context, in *ClusterStartupScriptRequest, opts ...grpc.CallOption) (*ClusterStartupScriptResponse, error) {
	out := new(ClusterStartupScriptResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/StartupScript", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) InstanceByIP(ctx context.Context, in *ClusterInstanceByIPRequest, opts ...grpc.CallOption) (*ClusterInstanceResponse, error) {
	out := new(ClusterInstanceResponse)
	err := grpc.Invoke(ctx, "/kubernetes.Clusters/InstanceByIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Clusters service

type ClustersServer interface {
	List(context.Context, *ClusterListRequest) (*ClusterListResponse, error)
	Describe(context.Context, *ClusterDescribeRequest) (*ClusterDescribeResponse, error)
	Create(context.Context, *ClusterCreateRequest) (*dtypes.LongRunningResponse, error)
	Update(context.Context, *ClusterUpdateRequest) (*dtypes.VoidResponse, error)
	Scale(context.Context, *ClusterScaleRequest) (*dtypes.LongRunningResponse, error)
	Upgrade(context.Context, *ClusterUpgradeRequest) (*dtypes.LongRunningResponse, error)
	Delete(context.Context, *ClusterDeleteRequest) (*dtypes.LongRunningResponse, error)
	ClientConfig(context.Context, *ClusterClientConfigRequest) (*ClusterClientConfigResponse, error)
	Instances(context.Context, *ClusterInstanceListRequest) (*ClusterInstanceListResponse, error)
	StartupScript(context.Context, *ClusterStartupScriptRequest) (*ClusterStartupScriptResponse, error)
	InstanceByIP(context.Context, *ClusterInstanceByIPRequest) (*ClusterInstanceResponse, error)
}

func RegisterClustersServer(s *grpc.Server, srv ClustersServer) {
	s.RegisterService(&_Clusters_serviceDesc, srv)
}

func _Clusters_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).List(ctx, req.(*ClusterListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Describe(ctx, req.(*ClusterDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Create(ctx, req.(*ClusterCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Update(ctx, req.(*ClusterUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Scale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterScaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Scale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/Scale",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Scale(ctx, req.(*ClusterScaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Upgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterUpgradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Upgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/Upgrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Upgrade(ctx, req.(*ClusterUpgradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Delete(ctx, req.(*ClusterDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_ClientConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterClientConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).ClientConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/ClientConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).ClientConfig(ctx, req.(*ClusterClientConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Instances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterInstanceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Instances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/Instances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Instances(ctx, req.(*ClusterInstanceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_StartupScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterStartupScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).StartupScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/StartupScript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).StartupScript(ctx, req.(*ClusterStartupScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_InstanceByIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterInstanceByIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).InstanceByIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubernetes.Clusters/InstanceByIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).InstanceByIP(ctx, req.(*ClusterInstanceByIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Clusters_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubernetes.Clusters",
	HandlerType: (*ClustersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Clusters_List_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _Clusters_Describe_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Clusters_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Clusters_Update_Handler,
		},
		{
			MethodName: "Scale",
			Handler:    _Clusters_Scale_Handler,
		},
		{
			MethodName: "Upgrade",
			Handler:    _Clusters_Upgrade_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Clusters_Delete_Handler,
		},
		{
			MethodName: "ClientConfig",
			Handler:    _Clusters_ClientConfig_Handler,
		},
		{
			MethodName: "Instances",
			Handler:    _Clusters_Instances_Handler,
		},
		{
			MethodName: "StartupScript",
			Handler:    _Clusters_StartupScript_Handler,
		},
		{
			MethodName: "InstanceByIP",
			Handler:    _Clusters_InstanceByIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

func init() { proto.RegisterFile("clusters.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1994 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x58, 0x4f, 0x73, 0xe3, 0x48,
	0x15, 0x2f, 0xd9, 0x49, 0x6c, 0x3f, 0x3b, 0x99, 0xa4, 0x93, 0xc9, 0x6a, 0x9c, 0x1d, 0x26, 0xab,
	0x59, 0x66, 0x4d, 0x76, 0x63, 0x67, 0xb3, 0xb3, 0xb5, 0xb3, 0x03, 0xcc, 0xb2, 0x71, 0xf8, 0x93,
	0x25, 0x4c, 0x05, 0x99, 0xd9, 0xab, 0x4a, 0x91, 0x3a, 0x1e, 0x11, 0x45, 0x2d, 0xba, 0xdb, 0xd9,
	0xc9, 0x4c, 0x85, 0xa2, 0xa8, 0xa2, 0x80, 0xe2, 0xc8, 0x57, 0x80, 0x23, 0xcb, 0x85, 0x33, 0x17,
	0xae, 0x54, 0x71, 0xe0, 0x2b, 0xf0, 0x2d, 0x28, 0xaa, 0xa8, 0x7e, 0x2d, 0xc9, 0xb2, 0x2d, 0x3b,
	0xf1, 0xc5, 0x25, 0xbd, 0xf7, 0xfa, 0xbd, 0x5f, 0xb7, 0xde, 0x9f, 0x5f, 0x1b, 0x56, 0xbc, 0x70,
	0x20, 0x24, 0xe5, 0xa2, 0x1d, 0x73, 0x26, 0x19, 0x81, 0xf3, 0xc1, 0x29, 0xe5, 0x11, 0x95, 0x54,
	0x34, 0xdf, 0xee, 0x33, 0xd6, 0x0f, 0x69, 0xc7, 0x8d, 0x83, 0x8e, 0x1b, 0x45, 0x4c, 0xba, 0x32,
	0x60, 0x51, 0x62, 0xd9, 0xdc, 0x54, 0x62, 0x5f, 0x5e, 0xc5, 0x54, 0x74, 0xf0, 0x57, 0xcb, 0xad,
	0xbf, 0x18, 0x70, 0xa7, 0xab, 0x9d, 0xf6, 0xa8, 0x94, 0x41, 0xd4, 0x17, 0xa4, 0x05, 0xab, 0x21,
	0xeb, 0x3b, 0x41, 0xe4, 0xd3, 0x57, 0x4e, 0xcc, 0xe9, 0x59, 0xf0, 0xca, 0x34, 0xb6, 0x8d, 0x56,
	0xcd, 0x5e, 0x09, 0x59, 0xff, 0x48, 0x89, 0x4f, 0x50, 0x4a, 0xf6, 0x60, 0x43, 0x59, 0x0a, 0xc9,
	0xb8, 0xdb, 0xa7, 0x4e, 0x18, 0x9c, 0x51, 0x19, 0x5c, 0x50, 0xb3, 0xb4, 0x6d, 0xb4, 0xca, 0x36,
	0x09, 0x59, 0xbf, 0xa7, 0x55, 0xc7, 0x89, 0x86, 0x3c, 0x83, 0xad, 0x0b, 0x16, 0x05, 0x92, 0xf1,
	0x20, 0x2a, 0x58, 0x58, 0xc6, 0x85, 0xf7, 0x86, 0x26, 0x63, 0xeb, 0xad, 0xbf, 0x55, 0xa0, 0x92,
	0xe0, 0x25, 0x04, 0x16, 0xe2, 0x97, 0x81, 0x9f, 0x60, 0xc3, 0x67, 0x25, 0x8b, 0xdc, 0x04, 0x41,
	0xcd, 0xc6, 0x67, 0xd2, 0x84, 0x6a, 0xcc, 0xd9, 0x65, 0xe0, 0x53, 0x8e, 0x01, 0x6a, 0x76, 0xf6,
	0x4e, 0x56, 0xa0, 0xc4, 0x84, 0xb9, 0x80, 0xd2, 0x12, 0x13, 0x64, 0x13, 0x96, 0x38, 0xed, 0x07,
	0x2c, 0x32, 0x17, 0x51, 0x96, 0xbc, 0x29, 0xbf, 0xaf, 0x59, 0x44, 0xcd, 0x25, 0xed, 0x57, 0x3d,
	0x93, 0xfb, 0x00, 0x1e, 0xa7, 0xae, 0xa4, 0xbe, 0xe3, 0x4a, 0xb3, 0x82, 0x9a, 0x5a, 0x22, 0xf9,
	0x5c, 0x92, 0xc7, 0xb0, 0x18, 0x06, 0xd1, 0xb9, 0x30, 0xab, 0xdb, 0xe5, 0x56, 0x7d, 0xff, 0x1b,
	0xed, 0xe1, 0xc7, 0x6a, 0x27, 0x5b, 0x68, 0x1f, 0x2b, 0x83, 0xef, 0x47, 0x92, 0x5f, 0xd9, 0xda,
	0x98, 0x58, 0xb0, 0xec, 0x33, 0x27, 0x62, 0xd2, 0xf1, 0x69, 0x48, 0x25, 0x35, 0x6b, 0xdb, 0x46,
	0xab, 0x6a, 0xd7, 0x7d, 0xf6, 0x9c, 0xc9, 0x43, 0x14, 0x29, 0x90, 0x42, 0xba, 0x72, 0x20, 0x4c,
	0xd0, 0x20, 0xf5, 0x1b, 0x79, 0x07, 0x1a, 0xfa, 0xc9, 0xf1, 0xdc, 0x81, 0xa0, 0x66, 0x1d, 0xb5,
	0x75, 0x2d, 0xeb, 0x2a, 0x11, 0x79, 0x00, 0xf5, 0xbe, 0x47, 0x9d, 0x98, 0xb3, 0x9f, 0x53, 0x4f,
	0x9a, 0x0d, 0xb4, 0x80, 0xbe, 0x47, 0x4f, 0xb4, 0x84, 0xb4, 0x61, 0x5d, 0xe1, 0x74, 0x04, 0xe5,
	0x97, 0x94, 0x3b, 0x97, 0x94, 0x0b, 0x75, 0x1a, 0xcb, 0x68, 0xb8, 0xa6, 0x54, 0x3d, 0xd4, 0x7c,
	0xa9, 0x15, 0x64, 0x1f, 0xee, 0x6a, 0x7b, 0x37, 0x94, 0xa7, 0xae, 0xa0, 0xd9, 0x8a, 0x15, 0x5c,
	0x81, 0xce, 0x7a, 0x89, 0x2e, 0x5d, 0xb3, 0x07, 0x1b, 0x7a, 0x8d, 0x74, 0xb9, 0xcc, 0x05, 0xb9,
	0x83, 0x4b, 0x08, 0x2e, 0xd1, 0xaa, 0x74, 0xc5, 0x7d, 0x80, 0x88, 0xf9, 0xd4, 0xf1, 0xd8, 0x20,
	0x92, 0xe6, 0xea, 0xb6, 0xd1, 0x5a, 0xb4, 0x6b, 0x4a, 0xd2, 0x55, 0x02, 0xf2, 0x2e, 0xac, 0xb8,
	0x71, 0x90, 0x62, 0x1e, 0xf0, 0xd0, 0x5c, 0x43, 0x57, 0x0d, 0x37, 0x0e, 0x34, 0xdc, 0x17, 0x3c,
	0x24, 0x5b, 0x50, 0xc3, 0xb0, 0x03, 0x41, 0xb9, 0x49, 0x74, 0x22, 0x28, 0xc1, 0x0b, 0x41, 0x39,
	0x79, 0x08, 0xcb, 0xa8, 0x8c, 0x5d, 0x21, 0xbe, 0x62, 0xdc, 0x37, 0xd7, 0xb5, 0x07, 0x25, 0x3c,
	0x49, 0x64, 0xe4, 0x2d, 0xa8, 0x78, 0xae, 0xe3, 0x51, 0x2e, 0xcd, 0x0d, 0x7d, 0xf2, 0x9e, 0xdb,
	0xa5, 0x5c, 0x92, 0x1d, 0xc0, 0xa3, 0x71, 0x4e, 0xa9, 0xcb, 0x29, 0x77, 0x24, 0x3b, 0xa7, 0x91,
	0x79, 0x17, 0x4d, 0xee, 0x28, 0xc5, 0x01, 0xca, 0x7f, 0xa6, 0xc4, 0xe4, 0x13, 0xa8, 0x8a, 0xa4,
	0xd4, 0xcc, 0xcd, 0x6d, 0xa3, 0x55, 0xdf, 0xdf, 0x2a, 0x48, 0x8d, 0xb4, 0x1a, 0xed, 0xcc, 0x98,
	0x3c, 0x86, 0xcd, 0x20, 0x12, 0xd2, 0x8d, 0x3c, 0xea, 0x70, 0xc6, 0xe4, 0x10, 0xeb, 0x5b, 0x18,
	0x69, 0x23, 0xd5, 0xda, 0x8c, 0xc9, 0x0c, 0xb3, 0x09, 0x95, 0xf4, 0x7c, 0x4d, 0x34, 0x4b, 0x5f,
	0xc9, 0x2a, 0x94, 0xc5, 0xf9, 0xc0, 0xbc, 0x87, 0x52, 0xf5, 0x98, 0xcf, 0xe8, 0xd3, 0x2b, 0xb3,
	0x39, 0x92, 0xd1, 0x07, 0x57, 0xcd, 0x27, 0x00, 0xc3, 0x84, 0x55, 0xcb, 0xcf, 0xe9, 0x55, 0x52,
	0x7d, 0xea, 0x91, 0x6c, 0xc0, 0xe2, 0xa5, 0x1b, 0x0e, 0xd2, 0xea, 0xd3, 0x2f, 0x4f, 0x4b, 0x4f,
	0x0c, 0x6b, 0x07, 0x36, 0x93, 0x7d, 0x1d, 0x52, 0xe1, 0xf1, 0xe0, 0x94, 0xda, 0xf4, 0x17, 0x03,
	0x2a, 0xa4, 0xf2, 0x32, 0xc8, 0x6a, 0x58, 0x3d, 0x5a, 0xff, 0x2b, 0xc1, 0x5b, 0x13, 0xc6, 0x22,
	0x66, 0x91, 0xa0, 0xe4, 0x51, 0x96, 0xf9, 0x06, 0x9e, 0xdc, 0x4a, 0x5b, 0xf7, 0xb4, 0x76, 0x0f,
	0xa5, 0x59, 0x25, 0xec, 0x42, 0x25, 0x69, 0x95, 0x88, 0xa5, 0xbe, 0xbf, 0x5e, 0x70, 0xc4, 0x76,
	0x6a, 0x43, 0xbe, 0x03, 0x0b, 0x22, 0xa6, 0x1e, 0x76, 0x87, 0xfa, 0x7e, 0xab, 0xc0, 0x76, 0x1c,
	0x49, 0xbb, 0x17, 0x53, 0xcf, 0xc6, 0x55, 0xcd, 0x7f, 0x1a, 0xb0, 0xa0, 0x5e, 0xc9, 0x7b, 0x70,
	0xc7, 0x63, 0x91, 0x74, 0x83, 0x88, 0xf2, 0x24, 0x55, 0x0d, 0x4c, 0xd5, 0x95, 0x4c, 0xac, 0xf3,
	0x75, 0x0b, 0x6a, 0x31, 0xf3, 0x13, 0x93, 0x12, 0x9a, 0x54, 0x63, 0xe6, 0x6b, 0xe5, 0x43, 0x58,
	0x56, 0x89, 0x1c, 0x78, 0x69, 0xba, 0x97, 0xd1, 0xa0, 0x91, 0x08, 0xb5, 0xd1, 0x3d, 0xa8, 0x72,
	0x2f, 0xd1, 0x2f, 0xa0, 0xbe, 0xc2, 0xbd, 0xcc, 0xb9, 0x64, 0xd2, 0x0d, 0x1d, 0x2f, 0x1e, 0x60,
	0x17, 0x2b, 0xdb, 0x55, 0x14, 0x74, 0xe3, 0x81, 0x6a, 0x11, 0x5a, 0x79, 0x41, 0x2f, 0x18, 0xbf,
	0xc2, 0x7e, 0x56, 0xb6, 0xeb, 0x28, 0xfb, 0x09, 0x8a, 0xac, 0x0f, 0x80, 0x24, 0x9b, 0x3e, 0x0e,
	0x84, 0x4c, 0xbf, 0xd3, 0x66, 0xee, 0xe4, 0xcb, 0xc3, 0x9e, 0x63, 0x45, 0xb0, 0x3e, 0x62, 0x3d,
	0xe7, 0x87, 0xea, 0x40, 0x35, 0x9d, 0x69, 0x66, 0x09, 0xfb, 0x64, 0xe1, 0x97, 0xca, 0x8c, 0xac,
	0x7f, 0x2c, 0xc2, 0x46, 0x22, 0xed, 0x62, 0x62, 0xa6, 0x00, 0xd3, 0xce, 0x6f, 0x4c, 0xe9, 0xfc,
	0xa5, 0xb1, 0xce, 0x9f, 0x76, 0xf4, 0x72, 0xae, 0xa3, 0x7f, 0x0b, 0x56, 0xbd, 0x90, 0x0d, 0x7c,
	0xc7, 0xe3, 0xd4, 0xa7, 0x91, 0x0c, 0xdc, 0x30, 0x99, 0x0d, 0x77, 0x50, 0xde, 0xcd, 0xc4, 0xe4,
	0x02, 0xee, 0x8e, 0x9b, 0x3a, 0xbe, 0x2b, 0x5d, 0x73, 0x11, 0x77, 0xf1, 0x69, 0xc1, 0x2e, 0x46,
	0xf0, 0xb6, 0xbb, 0xa3, 0x0e, 0x0f, 0x5d, 0xe9, 0xea, 0x41, 0xb0, 0xee, 0x4d, 0x6a, 0xc8, 0x8f,
	0xa0, 0x8a, 0x0d, 0x50, 0x50, 0x69, 0x2e, 0x61, 0x84, 0xdd, 0x1b, 0x23, 0x3c, 0x67, 0x3e, 0xed,
	0x51, 0xa9, 0xbd, 0x56, 0x22, 0xfd, 0x36, 0xbd, 0x61, 0x57, 0xe6, 0x6f, 0xd8, 0xd5, 0xa9, 0x0d,
	0x7b, 0xca, 0x18, 0xa9, 0x4d, 0x1b, 0x23, 0x13, 0x63, 0x0f, 0x26, 0xc7, 0xde, 0xfb, 0xb0, 0xf6,
	0x92, 0x09, 0x79, 0xe6, 0x7a, 0x52, 0x64, 0x1e, 0xf5, 0x8c, 0x5b, 0xcd, 0x14, 0xa9, 0xc3, 0x5c,
	0xdb, 0x6b, 0x8c, 0xb4, 0xbd, 0xe6, 0x0f, 0xc0, 0x9c, 0x76, 0xf6, 0xf3, 0xf4, 0xb4, 0xe6, 0x53,
	0x68, 0xe4, 0x4f, 0xf8, 0xa6, 0xb5, 0xe5, 0x7c, 0x3f, 0xfc, 0xbb, 0x91, 0x95, 0x4d, 0xcf, 0x73,
	0xc3, 0x99, 0x49, 0xdc, 0x83, 0x86, 0x9e, 0x7d, 0x2f, 0xdd, 0xa8, 0x4f, 0xd3, 0x32, 0xd9, 0x2b,
	0x9a, 0x19, 0x39, 0x57, 0xf8, 0xf5, 0xbb, 0x7a, 0x89, 0xce, 0x80, 0x7a, 0x34, 0x94, 0x34, 0x9f,
	0xc1, 0xea, 0xb8, 0xc1, 0x5c, 0x1b, 0x88, 0xb3, 0x2a, 0xd4, 0x1f, 0x67, 0xd6, 0x06, 0xda, 0xb0,
	0xce, 0x69, 0x48, 0x55, 0xae, 0x71, 0x8a, 0x09, 0xe1, 0x3b, 0x41, 0x8c, 0x3e, 0xab, 0xf6, 0x5a,
	0xa2, 0xb2, 0x13, 0xcd, 0x51, 0xac, 0xa2, 0x9e, 0x31, 0xee, 0xe9, 0xd2, 0xac, 0xda, 0xfa, 0xc5,
	0xea, 0xc2, 0x56, 0xba, 0x4d, 0x95, 0x6a, 0x83, 0xb8, 0xe7, 0xf1, 0x20, 0x96, 0x53, 0xe7, 0x88,
	0x82, 0xc2, 0x59, 0x98, 0x51, 0x41, 0xf5, 0x6c, 0x85, 0xf0, 0x76, 0xb1, 0x93, 0x39, 0xdb, 0xd6,
	0xbb, 0xb0, 0xec, 0xb1, 0xe8, 0x2c, 0xe8, 0x0f, 0x38, 0xd2, 0xec, 0x24, 0xc8, 0xa8, 0xd0, 0xfa,
	0x29, 0x34, 0x93, 0x68, 0x47, 0xc9, 0x64, 0x3e, 0xb8, 0x3a, 0x3a, 0xc9, 0x1d, 0xd5, 0x04, 0x7d,
	0x7d, 0x00, 0x75, 0xfa, 0x4a, 0x52, 0x1e, 0xb9, 0x61, 0x7a, 0x44, 0x35, 0x1b, 0x52, 0xd1, 0x51,
	0x6c, 0xbd, 0xce, 0x66, 0x63, 0xea, 0x72, 0x6e, 0xec, 0x9f, 0x40, 0x35, 0x25, 0x0a, 0xc9, 0x70,
	0x2c, 0xe2, 0x1f, 0x99, 0xfb, 0xcc, 0xd8, 0xda, 0xcb, 0xb6, 0xd3, 0x0d, 0x03, 0x1a, 0xc9, 0x2e,
	0x6e, 0x76, 0xc6, 0x97, 0xb7, 0xfe, 0x5b, 0xca, 0x3e, 0xda, 0xe8, 0x92, 0x39, 0x21, 0xb7, 0x0a,
	0x8f, 0xfb, 0xa0, 0x64, 0x1a, 0x63, 0x47, 0x4e, 0xbe, 0x99, 0xdd, 0x91, 0x1c, 0x9f, 0x5d, 0xb8,
	0x41, 0x94, 0xf4, 0xf7, 0xe5, 0x44, 0x7a, 0x88, 0xc2, 0x3c, 0x91, 0x5b, 0x18, 0x21, 0x72, 0x93,
	0x4c, 0x72, 0xb1, 0x80, 0x49, 0xee, 0xc0, 0x5a, 0x1a, 0x45, 0x91, 0x49, 0x07, 0x37, 0xbe, 0x94,
	0x0e, 0x0a, 0x54, 0x28, 0x52, 0xf9, 0x5c, 0x65, 0xff, 0x16, 0xd4, 0xd0, 0x06, 0x83, 0xe9, 0x1e,
	0x5b, 0x55, 0x02, 0x0c, 0x77, 0x0f, 0xf0, 0xd9, 0x51, 0x75, 0xa7, 0x9b, 0x69, 0x45, 0xbd, 0xff,
	0x98, 0x5e, 0xa9, 0x49, 0xad, 0x58, 0x03, 0x7d, 0x25, 0xb5, 0x7b, 0xdd, 0x3a, 0xeb, 0x89, 0x0c,
	0x5d, 0xdf, 0x07, 0xc0, 0xd5, 0x9a, 0x6e, 0xea, 0xbb, 0x00, 0x06, 0x43, 0xa2, 0x69, 0x9d, 0xc0,
	0xfd, 0xf1, 0xc3, 0xd7, 0x24, 0x64, 0x56, 0xb1, 0x6e, 0x41, 0xcd, 0x0f, 0xc4, 0xb9, 0x93, 0xbb,
	0x45, 0x55, 0x95, 0x40, 0x05, 0xb4, 0x3e, 0x9b, 0x48, 0xe8, 0x3c, 0x45, 0x50, 0x88, 0x93, 0x53,
	0xc9, 0xb9, 0xad, 0x27, 0x32, 0x74, 0xf0, 0xf5, 0xf0, 0xba, 0x99, 0x7a, 0xb8, 0xb9, 0x0e, 0xfc,
	0x89, 0x3a, 0x18, 0xde, 0xf3, 0xca, 0x39, 0xe8, 0x63, 0xc5, 0xb3, 0x30, 0x5e, 0x3c, 0xca, 0x20,
	0x88, 0x86, 0x06, 0xfa, 0xcb, 0x42, 0x2a, 0x3a, 0x8a, 0x53, 0x46, 0xbc, 0x94, 0x31, 0x62, 0xeb,
	0x57, 0x46, 0x96, 0xc1, 0xa3, 0x5b, 0x9e, 0x33, 0x83, 0x3f, 0x85, 0x5a, 0x5a, 0x47, 0x69, 0x07,
	0x9f, 0x59, 0x75, 0x43, 0x6b, 0xeb, 0xb7, 0x46, 0xd6, 0x6b, 0x5f, 0xc4, 0xfe, 0x0d, 0x8c, 0x67,
	0x62, 0x8e, 0x96, 0x26, 0xe7, 0x68, 0xfe, 0x02, 0x52, 0x9e, 0xe3, 0x02, 0x62, 0xfd, 0xae, 0x04,
	0x77, 0x33, 0x24, 0x7d, 0xee, 0xfa, 0x33, 0xa1, 0x4c, 0x25, 0x1a, 0xa5, 0xf9, 0x89, 0x46, 0x79,
	0x5e, 0xa2, 0xb1, 0x30, 0x8d, 0x68, 0x14, 0x92, 0x88, 0xc5, 0x9b, 0x49, 0xc4, 0xd2, 0x08, 0x89,
	0xd8, 0xff, 0x57, 0x03, 0xaa, 0xc9, 0x51, 0x08, 0xf2, 0x15, 0x2c, 0xa8, 0xa4, 0x20, 0x45, 0x57,
	0xfc, 0x5c, 0x81, 0x34, 0x1f, 0x4c, 0xd5, 0xeb, 0x6c, 0xb2, 0xda, 0xbf, 0xfe, 0xf7, 0x7f, 0xfe,
	0x58, 0x6a, 0x91, 0x47, 0x1d, 0x37, 0x8e, 0x85, 0xc7, 0x7c, 0xfd, 0x77, 0xce, 0x70, 0x55, 0xe7,
	0x72, 0xaf, 0xfd, 0x61, 0x27, 0x25, 0xc3, 0xe4, 0xf7, 0x06, 0x54, 0xd3, 0x9b, 0x09, 0xb1, 0x66,
	0x5e, 0x5b, 0x34, 0x82, 0x87, 0xb7, 0xb8, 0xda, 0x58, 0x8f, 0x11, 0x45, 0x9b, 0x7c, 0x70, 0x3b,
	0x14, 0x9d, 0x37, 0x83, 0xc0, 0xbf, 0x26, 0xaf, 0x61, 0x49, 0xd3, 0x4f, 0xb2, 0x7d, 0x13, 0x33,
	0x6d, 0x6e, 0xa5, 0x55, 0x72, 0xcc, 0xa2, 0xbe, 0x3d, 0x88, 0xa2, 0x20, 0xca, 0x86, 0x82, 0xf5,
	0x21, 0x86, 0x7f, 0xbf, 0x79, 0xcb, 0x43, 0x78, 0x6a, 0xec, 0xa8, 0xd8, 0xba, 0x34, 0x0a, 0x63,
	0x8f, 0x54, 0x4d, 0x73, 0x23, 0x8d, 0xfd, 0x25, 0x0b, 0xfc, 0x2c, 0xe8, 0x13, 0x0c, 0xba, 0x6f,
	0xed, 0xde, 0x76, 0xcf, 0x2a, 0xc5, 0xaf, 0x55, 0xec, 0xdf, 0x18, 0xb0, 0x88, 0xc4, 0x8b, 0x3c,
	0xb8, 0x81, 0x92, 0xcd, 0xde, 0xf6, 0x33, 0x44, 0xf0, 0xc4, 0xfa, 0x68, 0x2e, 0x04, 0x1d, 0xa1,
	0x02, 0x28, 0x1c, 0x7f, 0x30, 0xa0, 0x92, 0x54, 0x25, 0x79, 0xa7, 0xf0, 0x14, 0xf2, 0x15, 0x3b,
	0x1b, 0xcb, 0xf7, 0x10, 0xcb, 0x53, 0xeb, 0xe3, 0xf9, 0xb0, 0x0c, 0x74, 0x08, 0x85, 0xe6, 0x97,
	0xb0, 0x94, 0x74, 0x9b, 0xed, 0xc2, 0x94, 0xcb, 0x71, 0xc6, 0xd9, 0x50, 0x3e, 0x46, 0x28, 0x9d,
	0x9d, 0xf9, 0x3e, 0x0c, 0xf9, 0x93, 0x01, 0x8d, 0x3c, 0xe5, 0x20, 0x8f, 0x8a, 0x92, 0x72, 0x92,
	0xc6, 0x34, 0xdf, 0xbb, 0xd1, 0x2e, 0x01, 0xd6, 0x45, 0x60, 0xdf, 0x25, 0xdf, 0x9e, 0xef, 0x8c,
	0x3c, 0xf4, 0xb5, 0xab, 0x59, 0x0b, 0xf9, 0xb3, 0x01, 0xb5, 0xb4, 0xe7, 0x8b, 0x42, 0x8c, 0x05,
	0x83, 0xb6, 0x10, 0x63, 0xd1, 0x74, 0xb2, 0x7e, 0x88, 0x18, 0x3f, 0x27, 0x9f, 0xdd, 0x16, 0x63,
	0x7e, 0x7e, 0x5f, 0x77, 0xb2, 0x19, 0x44, 0xbe, 0x36, 0x60, 0x79, 0x84, 0x31, 0x93, 0x22, 0x0c,
	0x45, 0xc4, 0xbc, 0xd9, 0xba, 0xd9, 0x30, 0x41, 0xfb, 0x05, 0xa2, 0x3d, 0x24, 0x07, 0xf3, 0xf4,
	0x9d, 0x8e, 0xd0, 0xbe, 0x76, 0x05, 0x3a, 0xeb, 0xbc, 0x51, 0x3c, 0xff, 0x9a, 0xfc, 0xd5, 0x80,
	0x46, 0x9e, 0x74, 0xcf, 0x3c, 0xdb, 0x1c, 0x2b, 0x2f, 0xec, 0x90, 0xe3, 0x54, 0xdb, 0xb2, 0x11,
	0xe9, 0x31, 0xf9, 0xe2, 0xb6, 0x48, 0x15, 0xa9, 0x19, 0x9e, 0xe7, 0xee, 0xe9, 0xd5, 0x6e, 0x10,
	0x77, 0xde, 0xe4, 0xd8, 0xca, 0xf5, 0xe9, 0x12, 0xfe, 0x21, 0xff, 0xd1, 0xff, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x44, 0x5b, 0x80, 0x66, 0xe4, 0x17, 0x00, 0x00,
}
